### ISSUE TITLE
BIG BRONZE BOMB BUG

### ISSUE THREAD

**Issue by Rasgrul** [TeamEverlook/Everlook-BugTracker#1]
**Describe the bug**
I found two alliance aoe farming using this bomb it would just about instant kill lvl 55 mob with two of them throwing it. BIG bronze bomb would hit for 10+ hits each throw. NOT WORKING AS INTENDED 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/117347240/206836527-97505ff1-dadb-4fa1-a91d-9e5179dbed36.png)

**Additional context**

**Comment by Neto-WoW** [comment]
Thanks for the report. Can you be more clear on whats not intended? From a quick glance at this item it looks like it should do between 85 and 115 dmg in an aoe, which your screenshot seems to show. Any further info?

**Comment by CanvasDue** [comment]
Yes, you are right, it does 85 to 115 fire damage in aoe, but once player using this item it puts it on cooldown (1 minute). So you can't use it only once per 1 minute. This paladin can use more then 30 of it in 1 second. Have met him in WPL too and just got deleted, all combat log was spammed by damage from big bronze bombs, same thing as Rasgul showed. 
![Screenshot 2022-12-13 at 04 49 35](https://user-images.githubusercontent.com/120432983/207206562-d3d5c308-e50d-49d4-89a0-ae77c7075855.jpg)

**Comment by gl00m3r** [comment]
https://www.twitch.tv/j0raxd/clip/EsteemedHonorablePeppermintDancingBanana-Y5Dz1DvIL-V2o79w

**Comment by Neto-WoW** [comment]
Fixed on next update. Thanks again.
