### ISSUE TITLE
Arathi Basin reputation ticks are incorrect

### ISSUE THREAD

**Issue by HS-Disq** [TeamEverlook/Everlook-BugTracker#103]
**Describe the bug**
At the moment, Arathi Basin is rewarding 10 reputation every 330 resources tick. It seems to be the same as honor. This is wrong, it should be every 200 resources tick (150 at Call To Arms).

**Quest/Item/Spell Link**
https://vanilla-wow-archive.fandom.com/wiki/Arathi_Basin

**To Reproduce**
1. Go to Arathi Bashin
2. Wait for 200 resources
3. See nothing happen.
4. Wait for 330 resources
5. See honor (correct) and rep (incorrect) go up.

**Expected behavior**
Every 200 resources there should be a reputation tick.

**Comment by Gamemechanicwow** [comment]
It's part of the progression:

Patch 1.2 to 1.9 : The tick is 330 and 200 during weekend event.
Patch 1.10 + : The tick is 200 and 150 during weekend event.

**Comment by HS-Disq** [comment]
Then so it is. Closed.
