### ISSUE TITLE
Resto pots spammable without cooldown.

### ISSUE THREAD

**Issue by pooserver** [TeamEverlook/Everlook-BugTracker#110]
**Describe the bug**
Resto pots can still be spammed to remove dots.

**Additional context**
1.9 changes for elixir of poison resistance have been added so it does not remove blind in 1.4. Resto pots can still be spammed with no cooldown making it hard for locks and other classes in pvp.  This should be considered as well to be changed. thanks

**Comment by marshedpotato** [comment]
mate i think this is correct / intended. right now it is called restorative elixir, NOT restorative potion. as it's an elixir not a potion, it doesn't have 2min potion cooldown and can be spammed. in patch 1.5 (24th feb on everlook) it is renamed to restorative potion and as such will then be subject to 2m potion cooldown and no longer spammable.

**Comment by NiDiCi** [comment]
Hi @pooserver,

@marshedpotato is right, this is not an issue now but it is as said in the previous comment.
