### ISSUE TITLE
Rich Thorium Veins / Mining / Silithus spawns (probably world)

### ISSUE THREAD

**Issue by achilles305** [TeamEverlook/Everlook-BugTracker#111]
After a period of approximately less than 3 hours of a server restart, RTV nodes in Silithus seemingly stop respawning entirely, as if dwindling down to nothing. I do not farm elsewhere much in the world but this is not normal unless there was some weird 24 hour cool down integrated. Node respawn times should be 25 min, and understandably there should only be one per cluster (on reset there's usually more, thanks).

This isn't a case of "git gud" - other farmers are having this issue. This issue seemed like it was fixed about 2 weeks ago, now it seems like it's been repetitive in the last 72 hours.

Help.

**Comment by fixurshit** [comment]
true and real

**Comment by Solation1** [comment]
Seems to also be the case at Dark Whisper Gorge, i was only person there for over two hours - 0 spawns, guild said it seems to happen once server has been up a few days they stop respawning

**Comment by grechuu** [comment]
Hi,

Mining issue has been fixed 08.09.2023.
