### ISSUE TITLE
[Biznicks 247x128 Accurascope] doesn't work for melee

### ISSUE THREAD

**Issue by sh3ppard** [TeamEverlook/Everlook-BugTracker#116]
**Describe the bug**
[Biznicks 247x128 Accurascope](https://www.wowhead.com/classic/item=18283/biznicks-247x128-accurascope) **doesn't work for melee**.

It should work before `1.10` patch:
> This item used to effect melee swings and was one of the most saught after enchantsments by rogues and warriors alike. It was nerfed to only ranged attacks and made to be a balanced part of the game.
> 
> It was also taken out of the loot table for a long while until they fix it for ranged only. So, many engineers that had the pattern before they removed it from the loot table got to price gouge all they wanted as many servers only had a handful of people with it.
> 
> Source: https://www.wowhead.com/classic/item=18283/biznicks-247x128-accurascope#comments:id=4612

**Quest/Item/Spell Link**
[Biznicks 247x128 Accurascope](https://www.wowhead.com/classic/item=18283/biznicks-247x128-accurascope) 

**To Reproduce**
1. Go to Heroic Training Dummy at Orgrimmar
2. Equip enough hit (also bow/gun with this scope) for getting soft hit cap `9%`
3. Equip only maind-hand or 2H weapon
4. Start hit the dummy

**Expected behavior**
It must adds `3%` hit for melees too on early patches.
> - Patch 1.10.0 (2006-03-28): Now only affects ranged attacks.
> - Patch 1.4.0 (2005-04-19): Added.
> 
> Source: https://wowpedia.fandom.com/wiki/Biznicks_247x128_Accurascope

**Comment by achilles305** [comment]
let's fix this por favor?

**Comment by sh3ppard** [comment]
Bump.

**Comment by NiDiCi** [comment]
Since this has been fixed I will close the issue.
