### ISSUE TITLE
Flag Disappearing in WSG

### ISSUE THREAD

**Issue by Mooseheadd** [TeamEverlook/Everlook-BugTracker#13]
**Describe the bug**
Flag disappears when a hunter carrying it decides to feign death.

**To Reproduce**

**Expected behavior**
Flag should drop, but remain in-game when a player uses Feign Death, Vanish, Ice Block, Bubble.

**Screenshots**

**Additional context**

**Comment by Neto-WoW** [comment]
Fix pushed. Will be live ASAP.
