### ISSUE TITLE
Counting Out Time quest bug with Small Lockbox - Invalid Object

### ISSUE THREAD

**Issue by Idamajit** [TeamEverlook/Everlook-BugTracker#133]
**Describe the bug**
Invalid object on **every** Small Lockbox located in Andorhal.

**Quest/Item/Spell Link**
Counting Out Time

(https://classicdb.ch/?quest=4972)

**To Reproduce**
1. Go to Andorhal, in the Western Plaguelands
2. Click on Small Lockbox
3. Invalid Object error thrown

**Expected behavior**
I understand that these are supposed to be on timers and respawn after picked up. It's a very similar bug to the food/drink crates around Azeroth still showing but not being able to be picked up.

**Screenshots**

**Additional context**

**Comment by Simp-N** [comment]
This could likely be an issue with your cache. Try deleting your WDB folder.
https://everlook.org/faqs/faq-incorrect-game-data

*edit* I've had the same issue myself on previous pserver, and clearing the WDB fixed it. At least for the food and drink crates.

**Comment by Idamajit** [comment]
Thanks - that worked!
