### ISSUE TITLE
Valor's Rest flymaster

### ISSUE THREAD

**Issue by PickingANameIsHard** [TeamEverlook/Everlook-BugTracker#14]
Flymaster added in 1.3 to Valor's Rest Silithus is broken.

He doesnt have a green ! above his head like the usual undiscovered flymaster. You can talk to him, but he seems to think he's the Un'Goro flymaster, as seen on the screenshot.
When trying to fly anywhere you get the error message "you are too far away to interact with this NPC".

https://imgur.com/a/r2PZpSH

**Comment by Neto-WoW** [comment]
Seems to be fine to me.

Try clearing your wdb folder and disabling all addons.

![image](https://user-images.githubusercontent.com/79717052/208280058-197b5d35-6d91-4494-bfb8-b8f1b72f9400.png)
