### ISSUE TITLE
Death in Duel

### ISSUE THREAD

**Issue by UpDok** [TeamEverlook/Everlook-BugTracker#143]
I started a duel and won, but the other player died immediately after duel finished.
Player should have stayed alive with 1 hp.

More details if it helps:
We were in Camp Taurajo in the Barrens. And it seemed my pet imp might've made the last hit that killed the other player immediately after the duel ended.

**Comment by red-candle** [comment]
Unfortunately, this has always been so on private servers and is unlikely to ever be fixed. :(

**Comment by mroreo3** [comment]
This is technically a bug, but is also blizlike.
