### ISSUE TITLE
Molten Core NPC adjustments

### ISSUE THREAD

**Issue by lvangh** [TeamEverlook/Everlook-BugTracker#148]
**Describe the bug**
Issue 1 - Flame Imps damage output / Fire Nova cooldown
Issue 2 Core Hound packs are not attackable after death

**Expected behavior**
The flame Imps seem to all be casting Fire Nova at the same time with a too short CD or the proper scripting should be staggered based off the first cast.  this results in a player taking 500-700dmg * x number of Imps instantly. 

Core Hound packs (before Mag) when they reach 0HP should still be attackable, but the combat changes to "miss/dodge" etc. 

**Additional context**
I'll try to add Classic logs shortly of the Imps.

**Comment by NiDiCi** [comment]
Hi Ivangh,

I think this is something that has been fixed at this point, they are supposed to be dangerous. If you still have an issue with these mobs could you include a combat log or a video of the instance. It would also be helpful like you've written, a log or something describing your desired behavior. We can't promise we will nerf the content but if it's game breaking or not intended it will get changed.
