### ISSUE TITLE
Verog the Dervish not spawning

### ISSUE THREAD

**Issue by Aneuryzm** [TeamEverlook/Everlook-BugTracker#149]
Describe the bug:
The quest NPC for the quest Verog the Dervish does not spawn.

Expected behavior
After killing all the Kolkar centaurs in the area, the quest NPC should spawn, announced by a yell. Even after clearing the area multiple times, the NPC does not spawn.

**Comment by Everlooklox** [comment]
Verog the Dervish does spawn - I've done this on 4 characters already. You have to kill a TON of mobs to get him to spawn. The exact number is unknown as people could have been killing mobs for 30min before you got there and you may need to only kill 1 or 2 or you may need to kill 50+ i've had to clear the camp in front and 3 camps to the side over 15 times once.
