### ISSUE TITLE
Two mining nodes spawning on the same spot

### ISSUE THREAD

**Issue by Elitegamer010** [TeamEverlook/Everlook-BugTracker#150]
![WoWScrnShot_031023_191432](https://user-images.githubusercontent.com/30178237/224513266-d2c27639-7da6-402f-b78c-7c86445a6915.jpg)
![WoWScrnShot_031023_191434](https://user-images.githubusercontent.com/30178237/224513270-5c73a38d-bc49-4326-a6aa-054096028bc5.jpg)
![WoWScrnShot_031023_195130](https://user-images.githubusercontent.com/30178237/224513272-8b9533da-7f41-4bbf-b4f0-86ada485f671.jpg)
![WoWScrnShot_031023_195131](https://user-images.githubusercontent.com/30178237/224513275-81e2f1a3-56a4-4de6-a3f0-5fb3d7525f0f.jpg)

**Comment by NiDiCi** [comment]
This has been worked on and should now work as intended, make a new bug report if you find any issues with the mining nodes.
