### ISSUE TITLE
Shadow and fire vulnerability broken on warlocks since last update

### ISSUE THREAD

**Issue by mikixxx81** [TeamEverlook/Everlook-BugTracker#154]
**Describe the bug**
Since wednesday update, warlocks do not occasionally do additional 25/50/75/100% damage on mobs when mobs have either Curse of shadows or Curse of elements on them.

**Affected mobs**
So far i tested various mobs in Felwood/Durotar/Arathi Highlands and not once did, for example, shadowbolt do additional damage when Curse of shadows was cast on them. But there are other warlocks who noticed that in Warlock section on Discord.

**Expected behavior**
Spell cast on a mob with negative spell resistance (because they are affected with either Curse of Shadows or Curse of Elements) has a chance to increase in damage by 25/50/75/100% . That was all working as it should (and it was clearly marked in combat chat (see screenshot from couple of weeks ago) since the server start and it doesn't happen anymore since this wednesday.

**Screenshots**
![Shadowvuln](https://user-images.githubusercontent.com/128086937/225721841-95f1cd80-8465-4933-957a-282875479fb1.jpg)

**Comment by reddeffect** [comment]
Confirmed curses are broken since last week's update

**Comment by ghost** [comment]
Will be fixed after restart tonight
