### ISSUE TITLE
Casting a Curse of shadows on mob while shadowbolt

### ISSUE THREAD

**Issue by mikixxx81** [TeamEverlook/Everlook-BugTracker#155]
**Describe the bug**
Before wednesday update, you could cast shadowbolt on mob, and while shadowbolt was still in the air, cast Curse of shadows on it. Curse of shadows lands on mob, for example, 1 second before the shadowbolt does and that shadowbolt was affected by Curse of shadows. Now, if you do that, shadowbolt ignores Curse of shadows. Subsequent shadow spells cast on that mob are affected by Curse of shadows.

**Expected behavior**
If shadowbolt is fired at mob, and Curse of shadows is cast on same mob while shadowbolt is flying, Curse of shadows lands first and it should affect said shadowbolt which will hit mob a split second later. That's how it was working until wednesday patch.

**Comment by reddeffect** [comment]
confirmed issue is new since last week's update

**Comment by mikixxx81** [comment]
Working as intended as of 31.03.2023.
