### ISSUE TITLE
Barov Peasant Caller 1minute ready time

### ISSUE THREAD

**Issue by denis5396** [TeamEverlook/Everlook-BugTracker#16]
Barov Peasant Caller when equipped into your trinket slot will need 1 minute to be usable, instead of the usual 30 seconds. When 30 seconds pass by the trinket looks like it can be used, the normal 30s has passed, but when u actually want to press it, it will not work, you have to wait another 30s to be able to use it.

**Comment by Neto-WoW** [comment]
Will be fixed on next update.
