### ISSUE TITLE
Onyxia reset broken?!?

### ISSUE THREAD

**Issue by BananaFisshu** [TeamEverlook/Everlook-BugTracker#162]
**Describe the bug**
Me and my guildies did Ony on the 21.03.23 and we are still locked out till 29.03.23.

**Expected behavior**
The raid should have reset

**Comment by BananaFisshu** [comment]
raid id 116

**Comment by ghost** [comment]
Not seeing any issues with the reset system, no. Please look into your raid members to ensure you're not grouped with people with different instance locks.
