### ISSUE TITLE
Paladin Reckoning Bug

### ISSUE THREAD

**Issue by everlookgonnalosepeopletosom** [TeamEverlook/Everlook-BugTracker#164]
**Describe the bug**
After the last nigts reset paladins /sit macro doesnt give any reckoning stacks. I have been playing everlook since day one and only reason i am playing paladin for reckoning fun. Since the day one paladins had no issue about reck stacks but after the last maintance it doesnt work anymore. I am about to quit this server like every other EU's and everlook will stay only chinese pretty soon...

**Comment by ghost** [comment]
Will be fixed on next restart.
