### ISSUE TITLE
Resock times for Recipes and Formulas

### ISSUE THREAD

**Issue by Healtard** [TeamEverlook/Everlook-BugTracker#169]
**Describe the bug**
The restock timers are several hours long.

**Quest/Item/Spell Link**
(https://www.wowhead.com/classic/item=19445/formula-enchant-weapon-agility)

**Expected behavior**
Shorten the cd.

**Screenshots**
![image](https://user-images.githubusercontent.com/129583706/229273720-aa351160-d80a-4621-8684-155f88223b0d.png)

**Additional context**
I do get that they should be kinda rare BUT p.e. the timer for +15 agi enchant seems to be 4h+. That is absolutely mental on an 8k pop server. Since patch launch there have been tons of people camping it and by the looks of it we will have to park our chars there for at least a week straight to have a chance to buy it. Potentially even longer. Eventually the AD vendor has the same issue.

**Comment by Healtard** [comment]
![image](https://user-images.githubusercontent.com/129583706/229289306-4cdbdf45-8365-4d8b-b39c-bf07fd5eb9ac.png)

Also seems like the word spread and people are griefing now :) 👍

**Comment by NiDiCi** [comment]
Hi Healtard,

I'm sad to say but this is very common, all limited quantity vendor items have a internal timer. This is not an issue with the server but if you can find something pointing towards that this should be changed ( Other servers, classic, vanilla, old forum posts.
