### ISSUE TITLE
Plague upon thee termites not dispersing

### ISSUE THREAD

**Issue by ampletrolls** [TeamEverlook/Everlook-BugTracker#17]
**Describe the bug**

Whenever i plant the container on top of the box, it begins spraying butthe termites never release and complete quest.

**To Reproduce**

Click box, container fumes and releases termites.

**Expected behavior**

Place container on box and termites release, completing quest

**Screenshots**

none

**Additional context**

**Comment by Neto-WoW** [comment]
Quest works fine. You have to click on the barrel after you place it.
