### ISSUE TITLE
R14 Off-hands missing from the PVP vendor

### ISSUE THREAD

**Issue by LaurentJPL** [TeamEverlook/Everlook-BugTracker#172]
**Describe the bug**
The Rank 14 Off-hands are not available from the PvP vendor whilst they should be in-game right now.

**Quest/Item/Spell Link**
(https://classicdb.ch/?item=23456)

**To Reproduce**
Open the PvP vendor in Stormwind or Orgrimmar and observe the missing weapons.

**Expected behavior**
R14 Off-hands to be available from the PvP vendor.

**Screenshots**
negative

**Additional context**
People are R14 and can't even purchase the weapons that should be available.

**Comment by denis5396** [comment]
Also, make it purchasable with life time rank, people who got r14 and are not 14 now, can't buy any weapons.

**Comment by grechuu** [comment]
Hi LaurentJPL,

All of the items have been added to PVP vendors.
