### ISSUE TITLE
Witch Doctor Mau'ari is located in Everlook. She should be in Orgrimmar.

### ISSUE THREAD

**Issue by Azizxo** [TeamEverlook/Everlook-BugTracker#18]
**Describe the bug**
Witch Doctor Mau'ari is located in Everlook. 

**To Reproduce**
1. Go to Everlook
2. Click on Witch Doctor Mau'ri
3. Inspect screen and realize Witch Doctor Mau'ri is there.

**Expected behavior**
She is supposed to be in Orgrimmar, and be hostile to alliance players.

**Screenshots**

**Additional context**

https://wowwiki-archive.fandom.com/wiki/Witch_Doctor_Mau%27ari
https://wowwiki-archive.fandom.com/wiki/Patch_1.7.0

She should be in Orgrimmar until patch 1.7 and not offer Alliance her quests until patch 1.10

**Comment by HS-Disq** [comment]
This was changed for Everlook specifically to allow Alliance players to obtain Jujus.

**Comment by Azizxo** [comment]
Yes, that's the case but there is no good reason for it.

**Comment by HS-Disq** [comment]
OG Developers thought differently. It was specifically mentioned by them that this will be allowed.

**Comment by Azizxo** [comment]
Allegedly npc locations and quest availability are supposed to be progressive on this realm, why would there be made an exception in this case?

**Comment by ghost** [comment]
Looking into it with the team. I'll have info soon.

**Comment by ghost** [comment]
Any info? @Neto-WoW

**Comment by NiDiCi** [comment]
Intentionally changed by Wall and it was the same on other private servers, lh core that I know of. Since we are now past 1.7 I'm going to close this issue. If a new server was to be created by the everlook team this might be something to look over.
