### ISSUE TITLE
wowThe most heinous bug in 2004-2023, with a 100% increase in damage

### ISSUE THREAD

**Issue by nopvp1** [TeamEverlook/Everlook-BugTracker#181]
https://forum.everlook.org/t/wowthe-most-heinous-bug-in-2004-2023-with-a-100-increase-in-damage/2113
.............................
Difficult to accept, difficult to explain how such a bug could have occurred
+100%
+100%
Please fix it as soon as possible
THX
THX
THX...

**Comment by red-candle** [comment]
It's fine. I'm just gonna add them as "friend" and log out whenever they are online. At least ban them for abusing this bug?
