### ISSUE TITLE
Shaman Far Sight cannot be used consecutively.

### ISSUE THREAD

**Issue by shinefield** [TeamEverlook/Everlook-BugTracker#182]
**Describe the bug**
Shaman Far Sight cannot be used consecutively.
Cannot be seen for the second consecutive use

**Quest/Item/Spell Link**
spell Far Sight

**To Reproduce**
1. timeout 165ms
2. cast Far Sight
3. continue cast Far Sight

**Expected behavior**
Continuous use of the perspective should not be on yourself, should be on the target

**Screenshots**
http://www.shinefield.cn/temp/far.png

**Additional context**
no

**Comment by red-candle** [comment]
Yeah, this issue is for priest's mind vision as well. They have never worked properly on private servers. :(

**Comment by NiDiCi** [comment]
Hi Shinefield,

I'm not sure when this was fixed but this works now without issues. Please make another report if you are still having issues, make sure to include game version and if you can a video recording.
