### ISSUE TITLE
Rank14 weapons. Buying rank14 weapons after decreasing your rank is not possible.

### ISSUE THREAD

**Issue by Fantazista123** [TeamEverlook/Everlook-BugTracker#184]
I got my rank 14 on Everlook on 05.04.2023, character's name is Fantazista (alliance). Game Masters tell that you can buy your ranking gear even after rank decreasing. I trust in that and didn't buy second Grand Marshal's Dirk. I tried to buy it after my rank was decreased couple of times, i used both 1.12 and 1.14.0/1.14.1 clients and it didn't work for me. I tried to delete my WDB folders, it also didn't help. I created couple of tickets and Game Master Publius suggested me to make a bug report here. I hope you will help me, i just want to buy my second Grand Marshal's Dirk.

**Comment by grechuu** [comment]
Hey Fantazista123,

This is now fixed, let us know if its still an issue.
