### ISSUE TITLE
FIXED - SERIOUS - An Exclamation Mark "!" Over NPC Questgivers is not visible but it should be

### ISSUE THREAD

**Issue by peacebringer** [TeamEverlook/Everlook-BugTracker#185]
Hello there.

I want to report bug because you can't see yellow  " ! " (an exclamation mark) above NPC questgivers when your character is at certain level.

I tested out quest A Peon's Burden and at lvl 5 you could see " ! " over questgiver's head but when I was lvl 6 on my other character, there wasn't yellow " ! " but you could of course accept that quest and finish it. It's not that you are too big level for that quest, because when I picked it with both of my characters (both lvl 5 and lvl 6 characters), for both of my characters that quest was coloured yellow in my quest log and it was within my level range. 

It's the same thing for other quests too.

An Exclamation Mark "!" over NPC Questgivers should be visible for players even if that quest is green colorued in questlog for you when you accept it from questgiver.  An Exclamation Mark "!" over NPC Questgivers should not be visible once that quest is gray for you (when you are too high level for that quest, for example, if you are level 60 night elf and you come to Elwynn forest to do some quests, you will not see an Exclamation Mark "!" over NPC questgivers because you are too high level for them and if you accept them, they will be grey coloured in your quest log).

This is kinda serious bug for fresh or inexperienced players because you can literally skip unintentionally many quests because you can't see the usual yellow " ! " over NPCs heads.

Or is this normal at this current patch which I doubt it was normal (current patch of Everlook is 1.6 Blackwing Lair)

It's like it's someone changed in the code of server at which level an exclamation mark over NPC Questgivers " ! " won't be visible.

**Comment by Simp-N** [comment]
I also have this issue. Unfortunately I've not written down which quests were affected. At first I was unsure if it was addon-related but I doubt they can change wether the 3D model exclamation marks are visible.

**Comment by red-candle** [comment]
This is the first server that seems to have this issue. The ! should be showing for a certain range around the level of your character, but ALL quests that are below your level (even just -1) are hidden. (bug)

**Comment by magnapeccatrix** [comment]
This is game breaking bug, I am currently level 39 it still is a thing since the starting area. It makes it so difficult to find quest giver npcs without using add-ons to see which ones give quest.

**Comment by peacebringer** [comment]
We can close this issue.

I spoke with Neto (Everlook's developer) and he fixed this bug.

I tested it out and I can confirm this bug is fixed.

GG Neto 🙂👍
