### ISSUE TITLE
SERIOUS - Group Loot not working when your bag is full

### ISSUE THREAD

**Issue by peacebringer** [TeamEverlook/Everlook-BugTracker#186]
Hello.

I was in party and green item dropped, the interface with Need and Greed appeared, both of us clicked Greed for it and I won it, but my bags were full so I couldn't get the item, and while I was checking my bags to decide which item I will destroy so I can get one bagspace to loot that green item which I won on roll, other party member took the chance to quickly loot that green item for which he lost roll against me, so he somehow managed to loot that green item which he shouldn't be allowed to do it.

As far as I remember, that item should be on hold so no one can loot it except me, but it should be double checked for any case how that loot mechanic works in that described situation.

**Comment by NiDiCi** [comment]
Hello Peacebringer, 

Talked with Nothing about this as well. This is something that is quite know and I've experienced it on multiple servers. As far as I know this is intended, I know it can be frustrating but it is the way it's supposed to be. Make sure you got some space before you roll on things you need!
