### ISSUE TITLE
Alcor's Sunrazor soulbound

### ISSUE THREAD

**Issue by Exec-lol** [TeamEverlook/Everlook-BugTracker#19]
Hello, I received the loot "Alcor's Sunrazor", from a simple mob in the world, this dagger immediately became personal. I didn't wear it. Can you please fix this bug.

**Comment by Gamemechanicwow** [comment]
It's BOP until patch 1.9

**Comment by Exec-lol** [comment]
Can you give this dagger to our tank in the guild nickname "Tankerfury"? I don't want to resell it, just give it to the guild tank.

**Comment by Exec-lol** [comment]
My nickname in the game is Exec, warlock lvl 59
