### ISSUE TITLE
Gouge turns the enemy model.

### ISSUE THREAD

**Issue by Circkul89** [TeamEverlook/Everlook-BugTracker#196]
**Describe the bug**
Gouge turns the enemy model 90-180 degrees. But it's hitbox remains in place.

**Quest/Item/Spell Link**
https://www.wowhead.com/spell=1776/gouge

**Comment by red-candle** [comment]
Yeah, this has been like this on private servers since day 1. It might even be a client bug - I don't know since I never played a rogue on retail. :(

**Comment by Gamemechanicwow** [comment]
Orientation of NPCs in combat is handled by the client. The client normally makes them face their target. Gouge makes the monster lose its current target for the duration, and the client fallbacks to using the last known orientation.

TLDR: Client issue. Existed in vanilla and classic.

**Comment by red-candle** [comment]
I never played a rogue on vanilla (so I don't know how it worked then and there). However, before I gouge, the mob is always facing me, so once I gouge, even if it loses target, what is "the last known orientation"? Shouldn't it stay facing where I was when I gouged?

Right now, almost always when I gouge, it turns away.

Anyway, if it's a client bug then so be it. I know there are a lot of issues that were never addressed in two years, so it wouldn't surprise me if this is one of them.

**Comment by magnapeccatrix** [comment]
Hey new player on EL here, this problem needs a looking as it's severe and feels wrong. Not only gauge but cheap shot also does the same effect. Having played the game on retail vanilla and major vanilla private servers over the last two decades I don't recall this issue being existed on this level. Please take a look.

**Comment by Gamemechanicwow** [comment]
> Hey new player on EL here, this problem needs a looking as it's severe and feels wrong. Not only gauge but cheap shot also does the same effect. Having played the game on retail vanilla and major vanilla private servers over the last two decades I don't recall this issue being existed on this level. Please take a look.

It's a client issue. That's also emulated on classic. Blizzlike - and not related to the server.

classic references:
https://eu.forums.blizzard.com/en/wow/t/rogue-mobs-turning-when-gouged/84071
https://eu.forums.blizzard.com/en/wow/t/rogue-gouge-kidney-shot-turns-the-mob-180-degrees/98725
https://eu.forums.blizzard.com/en/wow/t/rogue-issue-mob-position-changes-after-gouge-kidney-shot/91228
https://eu.forums.blizzard.com/en/wow/t/rogue-bug-with-gouge/85506
https://eu.forums.blizzard.com/en/wow/t/backstab-you-must-be-behind-the-target-bug/97703
https://eu.forums.blizzard.com/en/wow/t/1-month-old-bugs/93022
https://us.forums.blizzard.com/en/wow/t/weird-rogue-thing/305852/15

Other references:
https://github.com/slowtorta/turtlewow-bug-tracker/issues/562
https://github.com/vmangos/core/issues/872
https://github.com/vmangos/core/issues/1199
