### ISSUE TITLE
Logging in Toggles PvP Mode Off

### ISSUE THREAD

**Issue by Newfriendfromwinter** [TeamEverlook/Everlook-BugTracker#2]
**Describe the bug**
A player who has manually set his PvP mode to enabled will have his mode set to disabled after logging in.

**To Reproduce**
```
0. Be in a friendly zone.
1. On a character, enter "/pvp" into the chat window.  You will now be PvP flagged because PvP is now set to on.
2. Log out in a friendly zone
3. Log in
4. Your PvP is set to off.
5. Wait 5 minutes.  Your PvP flag is now removed because PvP is set to off.
```

**Expected behavior**
The game should respect whether a player has manually opted into PvP, by making leaving it on if it is manual.

**Additional context**
Evidence (June 2006): https://wowwiki-archive.fandom.com/wiki/PvP_flag?oldid=164179

![image](https://user-images.githubusercontent.com/118998194/204701794-98bb5c39-7df9-4272-9887-fe8aa968596a.png)

**Comment by Newfriendfromwinter** [comment]
If this bug is fixed, there will be more players in the open world who are PvP flagged. For example, we'll have PvP-flagged duelists outside Stormwind/Orgrimmar.

Currently, we see an odd absence of PvP-flagged players in places like cities because it's too tedious to remain PvP flagged.

**Comment by Neto-WoW** [comment]
Thanks for the report. I think "permanently" means that it won't be removed after 5 minutes like other PVP actions. I don't see anything mentioning it will remain on after logout, and I personally dont remember that from Vanilla.

I'll discuss this with the team, but in the meantime if you have any further evidence of this persisting after logout, that would be great.

**Comment by Newfriendfromwinter** [comment]
> Thanks for the report. I think "permanently" means that it won't be removed after 5 minutes like other PVP actions. I don't see anything mentioning it will remain on after logout, and I personally dont remember that from Vanilla.
> 
> I'll discuss this with the team, but in the meantime if you have any further evidence of this persisting after logout, that would be great.

The feature persisted on Classic Vanilla.  Between that, the evidence presented, and how the feature is tedious in its current form, I think it's probable that there's a bug.

**Comment by Gamemechanicwow** [comment]
### Patch notes for 1.4

> The /pvp flag has been changed to a toggle. Now once /pvp is turned on, you will be flagged for PvP until it is turned off. The /pvp flag will remain even after logging out, so please remember to turn off the /pvp flag if you do not wish to engage in PvP. This option is only available to players on Normal and Role Play realms.

The changes to /pvp over time are interesting. While the above notes tell it should remain while being logged off, it also states it's not available on pvp realms. I assume the /pvp was altered again at a later patch.

**Comment by Neto-WoW** [comment]
We'll leave this as it is for now. Maybe in the future we'll revisit it but its not a priority at the moment.
