### ISSUE TITLE
Dampen Magic

### ISSUE THREAD

**Issue by MakMike** [TeamEverlook/Everlook-BugTracker#20]
Dampen magic reduce only half damage taken. 
For example, rank 4 with talent Magic Attunement (2/2) reduce only 45 magic damage.

**Comment by ghost** [comment]
Please provide more information. What you think is correct, and any evidence you can provide to prove your position.

**Comment by NiDiCi** [comment]
I tested Dampen magic rank 5 10174, it seems to work as intended. If you could elaborate on your issue with the current state of dampen magic following the template I will look into the issue again.
