### ISSUE TITLE
Some spell effects never fade

### ISSUE THREAD

**Issue by red-candle** [TeamEverlook/Everlook-BugTracker#208]
**Describe the bug**
Some spell effects never fade resulting in great frame rate drops, especially in long Alterac Valleys. (frost nova ice, hurricane clouds, entangling roots)
This bug has been around forever and is usually not present, but was enabled again on the morning of June 5th.

**Comment by Gamemechanicwow** [comment]
Sounds like this bug: https://nostalrius.org/viewtopic.php?f=76&t=30228

It was a common driver issue iirc. Try installing a different version.

**Comment by red-candle** [comment]
No, because this worked perfectly before June 5th. Why would my drivers keep graphics in memory and display them only in battlegrounds even after relogging with the character and the account?

The more likely explanation is that on the server, someone figured that since a spell effect has a duration, a message about the end does not need to be sent, thus saving on performance. The client, however, expects that message or it malfunctions and eventually crashes.

Right now, after every battleground, I end up in Orgrimmar where I receive the information about all the characters and their gear and I have to restart the game, getting all the info a second time after clearing the memory. How does this save on performance?

The linked post says nothing about a driver issue - looks like it was never fixed.

**Comment by Gamemechanicwow** [comment]
> No, because this worked perfectly before June 5th. Why would my drivers keep graphics in memory and display them only in battlegrounds even after relogging with the character and the account?

How would the driver/gpu know you have changed character? Why? Because of incompatibility.

> The more likely explanation is that on the server, 

Then more ppl would be affected. 

>someone figured that since a spell effect has a duration, a message about the end does not need to be sent, thus saving on performance. The client, however, expects that message or it malfunctions and eventually crashes.

Nope, that's not how spell effects work.

> Right now, after every battleground, I end up in Orgrimmar where I receive the information about all the characters and their gear and I have to restart the game, getting all the info a second time after clearing the memory. How does this save on performance?

I have no idea what this is supposed to mean?

> The linked post says nothing about a driver issue - looks like it was never fixed.

Nah, i guess most of the resources are not easily accessible anymore. But it was also brought up on several issue trackers and lh discord iirc.

Some questions you may want to ask yourself:

- Do other players have similar problems?
- Do the issue persist if I use a different computer with a different GPU?

**Comment by red-candle** [comment]
Whatever. This is "fixed" now. It is always the same on all private servers. It appears with an update and goes away with another.

I've had this happening on at least three different machines, operating systems and drivers (from different manufacturers).

**Comment by red-candle** [comment]
This shit is back! No, I haven't made ANY changes to my system and all automatic updates are off.
