### ISSUE TITLE
furbolg medicine pouch says target too low level

### ISSUE THREAD

**Issue by audenious** [TeamEverlook/Everlook-BugTracker#21]
hi,
i am level 38, when i use my furbolg medicine pouch (as i purchased from vendor, due to acquiring necessary reputation) it says "target too low level." i am the target, (which it shouldnt need a target anyway) and the item shouldnt have a level requirement either. please advise.
redridgehoss

**Comment by ghost** [comment]
Working as intended.

https://web.archive.org/web/20070102103440/http://wow.allakhazam.com/db/item.html?witem=16768
