### ISSUE TITLE
warrior whirlwind skill bug

### ISSUE THREAD

**Issue by dutianjie1990** [TeamEverlook/Everlook-BugTracker#212]
HI, I am a warrior player. I found the following problems when I was in the BWL and the MC. The attack range of the bloodthirsty skill is 5 yards. The attack range of the whirlwind  skill is 8 yards. When killing the ragnaros ,fallen Varastaz, Klomagus, and Nefarian, the whirlwind  will not cause harm within the normal attack range of the bloodthirsty skill. bloodthirsty skill can Longest Range Attack It works but the whirlwind is Not working .when i Close to the ragnaros and fallen varastaz Still invalid。It seems to only happen to the extremely large boss.please check it and thank you very much.

**Comment by grechuu** [comment]
Hi dutianjie1990,

As of recent database upgrade Whirlwind works now properly.
