### ISSUE TITLE
Seal of Wrynn stats not applying correctly

### ISSUE THREAD

**Issue by tarwy1** [TeamEverlook/Everlook-BugTracker#213]
**Describe the bug**
The Seal of Wrynn item from the stormwind quest line is only applying 2 stamina and 6 spirit as opposed to the 3 str, 3 agi, 4 stam, 4 int and 3 spirit in the tooltip

**Quest/Item/Spell Link**
https://www.wowhead.com/classic/item=2933/seal-of-wrynn

**To Reproduce**
1. Equip the ring
2. observer stats not applying correctly

**Expected behavior**
3 str, 3 agi, 4 stam, 4 int and 3 spi should be applied

**Screenshots**
images with and without ring shown:
![Screenshot-2023-06-17-214548 316](https://github.com/TeamEverlook/Everlook-BugTracker/assets/38536921/100523a6-3274-47f5-b551-3b23f8101c51)
![Screenshot-2023-06-17-214553 494](https://github.com/TeamEverlook/Everlook-BugTracker/assets/38536921/9966f087-f5f1-4440-a481-03b7a9521f4e)

**Additional context**
I am a gnome mage if that is relevant.

**Comment by Nabbie1** [comment]
stats are correct https://classicdb.ch/?item=2933-0

it gets updated in 1.9, delete wbd if using 1.12 to see correct stats
