### ISSUE TITLE
Sons of Hakkar are not tameable

### ISSUE THREAD

**Issue by fishertigerdragon** [TeamEverlook/Everlook-BugTracker#216]
**Describe the bug**
I tried to tame a son of hakkar last night 2023-06-23 in Zul Gurub. After having successfully cast the tame beast spell the mob did not turn into my pet. 

**To Reproduce**
1. Go to Zul Gurub
2. Cast tame beast on a son of hakkar after having cc:ed it with a freezing trap.

**Expected behavior**
The son of hakkar is to become my pet.

**Additional context**
I was in a raid when I tried taming it. I have not tried taming it when not in a raid.

**Comment by Gamemechanicwow** [comment]
Untameable until patch 1.9

https://wowwiki-archive.fandom.com/wiki/Patch_1.9.0#Hunters
