### ISSUE TITLE
Devour Magic

### ISSUE THREAD

**Issue by sneakytucky** [TeamEverlook/Everlook-BugTracker#22]
**Describe the bug**
Devour Magic (fel hunter spell) is purging when toggled off when set to attack. 

**Expected behavior**
Devour Magic is a spell with a toggle ability the pet does automatically when toggled on. 
But it continues to automatically cast when toggled off

**Comment by ghost** [comment]
I cant reproduce this unfortunately. Can you make sure you're clearing wdb and disabling all addons. Report back!

**Comment by Gamemechanicwow** [comment]
My guess is 1.14?

**Comment by sneakytucky** [comment]
yeah sorry about that, it's a 1.14 issue.
