### ISSUE TITLE
Resetting talents always costs 5g

### ISSUE THREAD

**Issue by red-candle** [TeamEverlook/Everlook-BugTracker#221]
**Describe the bug**
Resetting talents always costs 5g. Each reset should increase the price by 5g to a maximum of 50g.

**Additional context**
https://vanilla-wow-archive.fandom.com/wiki/Talent

"Since [patch 1.11](https://vanilla-wow-archive.fandom.com/wiki/Patch_1.11.0) there is a decay in the cost of such talent respecs:
The cost to unlearn talents will now decay over time. This cost will be reduced by a rate of 5 gold per month to a minimum of 10 gold."

**Comment by Nabbie1** [comment]
Not a bug, respec cost capped at 5g on this server

**Comment by red-candle** [comment]
So then it is not blizzlike?
