### ISSUE TITLE
Touch of Weakness is not applied when sapped

### ISSUE THREAD

**Issue by red-candle** [TeamEverlook/Everlook-BugTracker#224]
**Describe the bug**
Touch of Weakness is not applied when sapped. (or improve sapped)

**Quest/Item/Spell Link**
spell=19266
spell=19254

**To Reproduce**
1. Cast the buff.
2. Get sapped by improved sap.
3. The rogue does not resist the spell.
4. It is still stealthed.

**Expected behavior**
The rogue should get the debuff, hurt and leave stealth.

**Additional context**
https://www.wowhead.com/tbc/spell=19266/touch-of-weakness#comments:id=16698

**Comment by NiDiCi** [comment]
Me and nothing tested this.

The issue you are having does indeed happen but I believe that interaction is intended. Non damaging ability's should not trigger the touch of weakness, I believe this is working as intended. The same goes for "Cheap shot" and other non damaging abilities.

**Comment by red-candle** [comment]
Did you check the linked comment? Sure, it's from patch 2.0.1 but according to https://wowpedia.fandom.com/wiki/Touch_of_Weakness , it wasn't changed in that patch.

**Comment by NiDiCi** [comment]
Yes I read that after leaving my comment, I will look into it some more.

**Comment by NiDiCi** [comment]
I finnally got this tested on era and it works the same there, so I believe this was a bug later corrected by blizzard. If you can find something disputing that make another bug report.
