### ISSUE TITLE
No credit for tagged mob if NPCs do most damage

### ISSUE THREAD

**Issue by red-candle** [TeamEverlook/Everlook-BugTracker#226]
**Describe the bug**
When fighting an NPC, if most of the damage is done by NPCs, the player who has tagged/tapped the target gets no credit (exp/loot/honor/whatever).
This means that if an honor-giving elite in AV is mind controlled to fight another, there's a good chance that the MC target won't give honor (has happened twice) because most of the damage to it was done by another NPC (I assume).

**To Reproduce**
1. Hurt an enemy NPC just a little
2. Let some other NPC kill your target
3. Get no loot or experience

I used to be able to mind control an elite NPC to fight another elite. When they were at low health, I would release MC, fear both and kill them for all the rewards.

**Expected behavior**
Perhaps the experience should be restricted to the percentage of the damage not done by NPCs, but all the loot, reputation, honor and other rewards should be there.

**Additional context**
It's difficult to find proof, but perhaps this helps:
https://www.wowhead.com/classic/npc=412/stitches#comments:id=2800446

"(Patch 1.8.4)
Stiches went all the way to darkshire, where I kited him around with SW:P while the guards killed him.  In the end I came out with a Zealot Blade that I sold for 25g, I was happy :D"

**Comment by mroreo3** [comment]
Got loot when killed him with NPCs. Issue seems resolved.
