### ISSUE TITLE
Speedhacker keeps disconnecting others?

### ISSUE THREAD

**Issue by red-candle** [TeamEverlook/Everlook-BugTracker#229]
**Describe the bug**
For the past 3 days, I have been disconnected in battlegrounds during or right before combat. I didn't think much of it except that it's really weird since I haven't gotten disconnected in weeks.

(WSG & AB)

Today, right before it happened, I saw a player character swish by at 200 km/h right before I got DCed. I immediately logged back in and we were under attack. I had been defending without action for a few minutes.

I didn't think of screenshotting the player list, but will in the future.

**Comment by NiDiCi** [comment]
Hi Ifyousayso

This might have been a connection issue or someone was using some sort of outside software. If this happens again contact a gm if you think theres a player using hacks.
