### ISSUE TITLE
Winterfall's mobs no runecloth drop

### ISSUE THREAD

**Issue by Sadcowface** [TeamEverlook/Everlook-BugTracker#236]

**Comment by Sadcowface** [comment]
https://classicdb.ch/?npc=7438
https://classicdb.ch/?npc=7441
https://classicdb.ch/?npc=7439
https://classicdb.ch/?npc=10916
https://classicdb.ch/?npc=7442
https://classicdb.ch/?npc=7440
https://classicdb.ch/?npc=10738
None of them have runecloth in loot.

**Comment by Gamemechanicwow** [comment]
They don't drop runecloth until patch 1.9

"Jaedenar humanoids and demons in Felwood and Winterfall Furbolgs in Winterspring can now drop Runecloth."
https://wowwiki-archive.fandom.com/wiki/Patch_1.9.0#Items

**Comment by Sadcowface** [comment]
Ok. its closed, thx
