### ISSUE TITLE
Horde Warbringers are missing

### ISSUE THREAD

**Issue by red-candle** [TeamEverlook/Everlook-BugTracker#237]
**Describe the bug**
Since this morning, Horde Warbringers seem to have been removed from all Horde cities.

**Quest/Item/Spell Link**
npc 15350

**Comment by red-candle** [comment]
Horde Warbringers are back (the one in UC anyway), but it has no quests. :(

**Comment by grechuu** [comment]
Hi ifyousayso,
The npc are in the citites.
