### ISSUE TITLE
Vanish doesn't removes effects on NPCs

### ISSUE THREAD

**Issue by sh3ppard** [TeamEverlook/Everlook-BugTracker#24]
**Describe the bug**
When there is a fight with a mob and bleeding effects are hanging on him (Rupture / Garrote) and in the same time someone of players attacks you then you try to escape from him using Vanish for it but fail. Because those effects do not disappear from the mob (as always when you fight with a mob solo) and when the bleeding tick enters into a state of combat and the mob start chasing you. Doesn't matter in stealth you or not. If you trying to use second vanish then it drops combat for a while until the next tick of bleeds happens.

**To Reproduce**
1. Start fight with a mob and use bleeds.
2. Someone of enemies attacks you.
3. Use Vanish for escape.
4. ???
5. Profit.

**Expected behavior**
I don't know if that is bug but it looks like.

**Comment by ghost** [comment]
I believe this is working as intended. Bleed effects wont disappear until a creature evades/leaves combat.
