### ISSUE TITLE
Lava jump

### ISSUE THREAD

**Issue by Neuroncz** [TeamEverlook/Everlook-BugTracker#241]
**Describe the bug**
It is possible to bypass parts of the instances using the so-called Lava jumping, by jumping on the lava. The lava should kill you. Many players have better equip than they deserve due to this bug.

**Quest/Item/Spell Link**
https://www.wowhead.com/classic/zone=1584/blackrock-depths
https://www.wowhead.com/classic/zone=2717/molten-core

**Comment by mroreo3** [comment]
This is intended in WoW For lava jumping in vanilla.
