### ISSUE TITLE
Free Knot! Quest does not spawn recipe box

### ISSUE THREAD

**Issue by edgeucated** [TeamEverlook/Everlook-BugTracker#248]
**Describe the bug**
When you use turn in the Gordok Shackle key to knot for the Free Knot! Quest, the box with tailoring/leatherworking recipes & materials does not spawn.

**Quest/Item/Spell Link**
https://classicdb.ch/?quest=7429

Example:  https://www.wowhead.com/classic/quest=5904/a-plague-upon-thee

**To Reproduce**
Get Gordok Shackle key
Turn in to Knot Thimblejack for the Free Knot Quest
No Box containing recipes/materials spawns

**Expected behavior**
A box containing tailoring/leatherworking recipes should spawn.

**Comment by TeamEverlook** [comment]
This should be fixed as of last tuesday. Have you checked since?

**Comment by edgeucated** [comment]
Just checked now and it's working, thank you!
