### ISSUE TITLE
Voidwalker has Imp abilitys

### ISSUE THREAD

**Issue by BananaJoeJo** [TeamEverlook/Everlook-BugTracker#249]
Since Yesterday my Voidwalker has Imp abilitys. i dont know how it happend, it was just there after i logged in yesterday.
![WoWScrnShot_081223_184622](https://github.com/TeamEverlook/Everlook-BugTracker/assets/142106611/6f4721f0-d429-4a74-80a6-068cd1ae9e66)
![WoWScrnShot_081223_184611](https://github.com/TeamEverlook/Everlook-BugTracker/assets/142106611/210f10cf-aa22-46dd-a785-7fc0a8b97105)

**Comment by DanWizrd** [comment]
Please open a ticket in-game to resolve this issue.
