### ISSUE TITLE
Voidwalker attacking from several yards away

### ISSUE THREAD

**Issue by Cyanidexx** [TeamEverlook/Everlook-BugTracker#251]
**Describe the bug**
Enemy player voidwalker gets aggroed from a very long distance

**To Reproduce**

1. After dying, go to maximum distance of your corpse, ressurect and stealth immediately. The voidwalker will start running to you without even having targetted you. The lock doesnt target the player either

**Expected behavior**

The voidwalker should not attack an enemy player at this long range. Even if its set on aggressive mode, the distance is way too long to get aggroed under normal circumstances. Both players are 60

**Additional context**

I got suspicions that the enemy player was cheating, because after getting help from a friend, we killed him, he ressed and appeared on a far away hill. He didnt use invisibility pot. It was like he graveyard ressed. Also there is no way to go to the specific hill so soon.

Thanks a lot in advance!

**Comment by NiDiCi** [comment]
Hi Cyanidexx,

I'm not really sure what we can test or change server side / ptr / QA. If you could get a video or something more specific on the game side that we can look at I will do so again. On the side that this might be a cheater, please make a ticket on discord and contact a GM.
