### ISSUE TITLE
The game character has abnormal speed

### ISSUE THREAD

**Issue by Damon19880808** [TeamEverlook/Everlook-BugTracker#252]
**Describe the bug**
Everlook account number: damon0105,  damon0106
ID name: Unknow(damon0105)
               Alliance(damon0106)
The game character was speed up suddenly when it after one trip flight.
The Alliance(damon0106) has this bugs in the last week, and the account was locked by GM.
Now I re-created a new account Unknow under damon0105,  the same issue happened again.
Pls help check the background records under Unknow(damon0105) from 20:00 to 20:15 in Aug 18th, 2023.

**Comment by Damon19880808** [comment]
Everlook account number: damon0105, damon0106
ID name: Unknow(damon0105)
The game character was speed up suddenly when it after one trip flight.
I restarted the game, found it will be speed up after each flight, the only way to recover is to be wolf or ride a horse.
I cannot contact PM to fix this issue.

**Comment by DanWizrd** [comment]
This is a GM issue and bans can be appealed on the Website.
