### ISSUE TITLE
Barbed Thorn Necklace should be BoE

### ISSUE THREAD

**Issue by itsthehorn** [TeamEverlook/Everlook-BugTracker#253]
**Describe the bug**
In all Vanilla databases I see, Barbed Thorn Necklace is BoE.  In game currently, it is BoP.  I believe it should be changed to BoE to be properly itemized.

**Quest/Item/Spell Link**

https://www.wowhead.com/classic/item=18289/barbed-thorn-necklace#comments

https://classicdb.ch/?item=18289

**To Reproduce**
Item checked in game and confirmed it is currently BoP by typing in chat:

/script DEFAULT_CHAT_FRAME:AddMessage("\124cff0070dd\124Hitem:18289:0:0:0:0:0:0:0:0\124h[Barbed Thorn Necklace]\124h\124r");

**Expected behavior**
Item should be itemized as BoE

**Screenshots**

![image](https://github.com/TeamEverlook/Everlook-BugTracker/assets/141683772/6295d9fc-3f70-4ce9-8d4c-daddd6ce71e8)

**Additional context**
I do not see item changing from BoP to BoE in patches that actually occurred in original WoW.  So, I do not think this issue will self correct in a future patch.  I think it may need to be manually changed to BoE by a developer.

**Comment by Retrexwow** [comment]
Barbed Thorn Necklace
It's BOP until Patch 1.9 (Current patch 1.8)

Proof:
Date: 2005-dec-10
https://web.archive.org/web/20051210175525/http://wow.allakhazam.com:80/db/mob.html?wmob=11461
Date: 2006-jan-09
https://web.archive.org/web/20060109004157/http://wow.allakhazam.com:80/db/mob.html?wmob=11461
*Place the mouse over the item to get the tooltip with the Item information

According to https://wowpedia.fandom.com/wiki/Patch#Vanilla
Patch 1.9 was implemented 2006-Jan-03.

**Comment by itsthehorn** [comment]
Thanks much for the info Retrexwow!  I (apparently incorrectly) thought that, because https://classicdb.ch/?item=18289 only showed patch history for the item with changes going from patch 1.3 to 1.4 (where nature damage was increased) - with the item showing there for both patches as BOE, that it must have been BOE as far back as 1.3/1.4.  But if Allakhazam is showing it as BOP as of 1.8, I agree with your comment, and will look for it changing to BOE in the next patch (1.9) on Everlook.  I'll close this Issue.  Thx again!
