### ISSUE TITLE
Second shard of the scale being removed from bags after 1.8

### ISSUE THREAD

**Issue by Retrexwow** [TeamEverlook/Everlook-BugTracker#254]
Second shard of the scale being removed from bags after 1.8

Before the patch 1.8 the Item Shard of the scale was not unique, which it means that you could have 2 or more of this items.
After 1.8 they became unique, which it means a player cant Loot 2 of this items anymore, but using wowhead comments as reference if you get 2 of this trinkets prio the patch 1.8 you should be able to keep both and equip them.

Unique mechanic means you can only loot 1 of this items, later in TBC patch Blizzard implemented the Label Unique-equip which makes unable the same item twice

References:
https://www.wowhead.com/classic/item=17064/shard-of-the-scale
https://imgur.com/a/52Jk2Du

**Comment by ghost** [comment]
We've made this no longer unique as of tomorrows maintenance.
