### ISSUE TITLE
Dire Maul East bonfire removing LoS

### ISSUE THREAD

**Issue by HS-Disq** [TeamEverlook/Everlook-BugTracker#26]
**Describe the bug**
In the room with Lethendris in Dire Maul - East, if you stand on the bonfire, it removes the walls and all the mobs on the other side are pulled. This is a very old vmangos bug that never got fixed.

**To Reproduce**
1. Go to Dire Maul - East, Lethendris' room
2. Stand on a bonfire next to a wall.
3. Result.

**Expected behavior**
The wall stays solid and stays LoS.

**Comment by Gamemechanicwow** [comment]
It's unrelated to the bonfires. It's the Warpwood Crushers on the opposite side that have an OOC pulse that targets random players and ignores LOS.

**Comment by HS-Disq** [comment]
Not sure about that. Cuz you can stand to the wall and nothing happens. When you go on the bonfire, it seems to be able to see you.
