### ISSUE TITLE
Slice and dice bug abuse on 1.14

### ISSUE THREAD

**Issue by Cyanidexx** [TeamEverlook/Everlook-BugTracker#266]
**Describe the bug**
Slice and dice ability can be used when targetting an enemy without having any combos on the target

**Spell Link**
https://www.wowhead.com/classic/spell=6774/slice-and-dice

**To Reproduce**
Steps to reproduce the behavior
1. Make a rogue
2. Target an enemy
3. Use slice and dice. You will get a 1 combo point slice and dice duration, without having to use a combo generating ability

**Expected behavior**
A rogue should not be able to use finishing moves without combo points. Slice and dice is a finishing move and it should require combo points present on the target to be used

This bug applies only to 1.14 client, which it has-WHO KNOWS-how many more and perhaps more important bugs

**Comment by grechuu** [comment]
Hi Cyanidexx,

This bug has been fixed.
