### ISSUE TITLE
Rescue From Jaedenar  Don't get out of the cage

### ISSUE THREAD

**Issue by zk202310** [TeamEverlook/Everlook-BugTracker#276]
**Describe the bug**
Rescue From Jaedenar  NPC  She doesn't come out of her cage

**Quest/Item/Spell Link**

https://classicdb.ch/?quest=5203

**To Reproduce**
Killed Arko'narin  still can't work    The problem lies in EA.

**Comment by mroreo3** [comment]
Just need the key to start the quest, cannot just open cage. 
https://classicdb.ch/?item=13140
If you have video of that, with key still not working. Please provide.
