### ISSUE TITLE
Chillwind Camp Scourgestone NPC not working

### ISSUE THREAD

**Issue by HS-Disq** [TeamEverlook/Everlook-BugTracker#28]
**Describe the bug**
In Chillwind Camp, you can turn in Scourgestones. The Minion's Scourgestones work, but the Invader and Corrupter does nothing. The quests are available, you can go to the final screen, but once pressing Complete Quest, nothing happens.

**To Reproduce**
1. Go to Chillwind Camp
2. Click on the Argent Dawn NPC
3. Scroll down to Invader's / Corrupter's Scourgestone.
4. Try and complete it.

**Expected behavior**
The quest is completed, +25 rep to Argent Dawn is added and you receive an Argent Dawn Valor Token.

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1630/files#diff-fa8449b336dbb842bbfc6e6f6b3783242d56f253342b4435e26d85d979ff2dd0R252
