### ISSUE TITLE
Elixir of brute force recipe disappeared from the alchemy list

### ISSUE THREAD

**Issue by Cyanidexx** [TeamEverlook/Everlook-BugTracker#282]
So, the title says everything. I had bought the recipe off the AH, i learned it (yes, i am sure i did, since i had also crafted several of them) and now I cannot find it. I have also opened a ticket, looking forward to seeing what is going on. Thanks a lot in advance!

**Comment by red-candle** [comment]
Nothing is going on. I don't think that the developers are reading any of these posts. The issues tracker seems to be a standard feature added to all private servers, but unless a bug bothers the developer, nothing will get done. :(

**Comment by grechuu** [comment]
Most likely a server rollback, make a ticket please.
