### ISSUE TITLE
Broken: Hazza'rah's Charm of Healing + Divine Fury

### ISSUE THREAD

**Issue by red-candle** [TeamEverlook/Everlook-BugTracker#283]
**Describe the bug**
Hazza'rah's Charm of Healing + Divine Fury 5/5 results in 1.8s heals, not 1.5s. The original spell casting time is 3s.
3s x 0.6 = 1.8s
But with Divine Fury 5/5, it should be:
2.5s x 0.6 = 1.5s

How can I tell? The spell finishes casting after 1.5s, but its cooldown is 1.8s?! When trying to recast it, the client tries and the server replies "Spell is not ready yet" (every time, not lag related).

**Quest/Item/Spell Link**
https://www.wowhead.com/classic/spell=18535/divine-fury
https://www.wowhead.com/classic/spell=10965/greater-heal
https://www.wowhead.com/classic/item=19958/hazzarahs-charm-of-healing
https://www.wowhead.com/classic/item=19958/hazzarahs-charm-of-healing#comments:id=2698187
https://www.wowhead.com/classic/item=19958/hazzarahs-charm-of-healing#comments:id=2698411

**To Reproduce**
1. Add points to the talent
2. Use the trinket
3. Cast Greater Heal (4)

**Expected behavior**
Hazza'rah's Charm of Healing + Divine Fury 5/5 should cast Greater Heal (4) at 1.5s (global cooldown).

**Comment by grechuu** [comment]
GCDprevents you from casting it again, GCD is around 1.5 sec
