### ISSUE TITLE
Starving Bonepaw is giving x5 more XP than they should

### ISSUE THREAD

**Issue by Simp-N** [TeamEverlook/Everlook-BugTracker#286]
**Describe the bug**
The [Starving Bonepaw](https://classicdb.ch/?npc=4689) in Desolace wander in packs of 5. Despite wandering in packs they're still very easy to defeat since their HP and damage is but a fraction - about a third - of what other mobs at the same level have. The XP they give should also be a lot less than what they're currently giving on Everlook. 

When I killed them mostly recently, on a lvl 37 character, I got 115 xp from a lvl 31, and 134 xp from a lvl 32. This is what a normal mob at that level should give to my lvl 37. Since they're so easy to kill it's very easy xp, especially if you have some form of AoE.

**To Reproduce**
Simply go to Desolace on a character that'll get XP from ~31 mobs and kill them.

**Expected behavior**
In [this video](https://youtu.be/zg9LG_DHS94?si=yR5R3pu0KC_kRQp-&t=60), which is from Classic, you'll see a lvl 32 priest killing the hyenas, and getting 34 xp from lvl 30, and 38 xp from a lvl 31. Now, if we compare this XPs to what mobs at these lvls would normally give a lvl 32 player, which is 171 and 188 respectively, it appears to be very close to 1/5. Basically, 171 / 5 = 34.2, and 188 / 5 = 37,6, and then rounded. 

I don't know if this fix is as simple as changing the Starving Bonepaw's xp_multiplier in the database from 1 to 0.2, but I suspect it might be.

I tried finding something about them from actual vanilla but got virtually nothing.

Thanks for reading.

*EDIT*
I'd like to add that [Bonepaw Hyena](https://classicdb.ch/?npc=4688) and [Rapid Bonepaw](https://classicdb.ch/?npc=4690), who also wander in packs of 5 and have very low health and damage, also give full XP. I've not found an example from Classic to see how much XP they give there.

**Comment by grechuu** [comment]
Hey Simp-N,

This is intentional, on LH core these dog packs gave the same amount of exp as on Everlook, on Cassic their xp was lowered.
