### ISSUE TITLE
Target dummies - Stuck in combat

### ISSUE THREAD

**Issue by Silverfalll** [TeamEverlook/Everlook-BugTracker#287]
"Often" getting stuck in combat for long periods of time. Sometimes it's just a minute, sometimes I go afk to come back to it still not being dropped. At those times i need to walk wquite far away (render distance?) - in SW i walk to the nearest gatehouse out of old town, and then it will dropp.
I have experienced this with 1.12 and new winterspring 1.14 client.

**Comment by red-candle** [comment]
Also, combat dummies should not exist at all.

**Comment by grechuu** [comment]
Hi [Silverfalll,

Target dummies are a custom feature from past developer, this is not a bug, just move away from them to drop combat.
