### ISSUE TITLE
It looks like Ambassador Flamelash in BRD need to be fixed.

### ISSUE THREAD

**Issue by Neuroncz** [TeamEverlook/Everlook-BugTracker#289]
**Describe the bug**

We recently had this boss with our guild and he seemed a bit bad because the spawned ads were stuck and didn't increase the boss's power like in this video.

https://www.youtube.com/watch?v=VC039Lty50E

**Comment by NiDiCi** [comment]
Hi Neuroncz,

I tested this today together with nothing and it works without issues. Send in another report if you still have the same issue.
