### ISSUE TITLE
[AQ40] With respect to Light's Hope,  Pre Twin Emps Trash behavior is wrong.

### ISSUE THREAD

**Issue by g-valentino** [TeamEverlook/Everlook-BugTracker#294]
Video: https://www.youtube.com/live/H6RHc679b7Y?si=Z7Z3pNz9Q3NMDByH

Timestamps:

3h 15m 22 sec raid is pulling anubisath after huhuran. Notice how they can see each other (not IN LOS) and they DONT CHAIN. In everlook at the moment they have to be LOSed from each other so they dont pull, this is wrong and is a just wasting raiders time.

The expected behavior is as seen, so long they are far from each other they shouldnt chain.

**Comment by NiDiCi** [comment]
Hi Sinn,

This has now been fixed and should be working as exspected.
