### ISSUE TITLE
Scarab mount gcd

### ISSUE THREAD

**Issue by bugFeatures** [TeamEverlook/Everlook-BugTracker#299]
**Describe the bug**
If you do not use an auto dismount addon and instead manually do it with a keybind thats on your action bar - you cannot dismount within the GCD. 
While with any other mount you can dismount any time you want, even if the mount is on GCD.

**Quest/Item/Spell Link**
https://www.wowhead.com/classic/item=21176/black-qiraji-resonating-crystal

**To Reproduce**
(this is on 1.12 client)
https://streamable.com/x1jmou

**Expected behavior**
The scarab mount should have the same mechanics as a normal mount.

**Comment by NiDiCi** [comment]
Hi Bugfeatures,

Tested this on 1.14 and asked a person with this mount to test it on main server with 1.12. I do not have any problems dismounting during the gcd. If this keeps being a problem or you can explain further what the problem is, make a new ticket.
