### ISSUE TITLE
holy shock + Illumination talent mana bug

### ISSUE THREAD

**Issue by roundabout1728** [TeamEverlook/Everlook-BugTracker#3]
**Describe the bug**
Mana is not properly refunded from Illumination talent for holy shock critical hits. Previously illumination was bugged to return mana not for the previously cast spell, but the spell cast afterward. That bug seems to be fixed but holy shock is not

**To Reproduce**
1. Cast divine favor
2. cast holy shock
3. no mana is refunded

**Expected behavior**
The holy shock mana cost should be refunded since it was a critical hit.

**Screenshots**
https://imgur.com/a/eRTRJMG

**Additional context**

**Comment by Gamemechanicwow** [comment]
Fixed in vmangos here:
https://github.com/vmangos/core/pull/1733

**Comment by Neto-WoW** [comment]
Will be fixed on next update 👍
