### ISSUE TITLE
Nifty Stopwatch puts Arena Grand Master trinket on 5min cooldown

### ISSUE THREAD

**Issue by Skylisios** [TeamEverlook/Everlook-BugTracker#305]
Nifty Stopwatch puts Arena Grand Master trinket on 5min cooldown

Nifty Stopwatch : https://www.wowhead.com/classic/item=2820/nifty-stopwatch
Arena Grand Master : https://www.wowhead.com/classic/item=19024/arena-grand-master

**Comment by NiDiCi** [comment]
Tested this a couple of times but I cannot reproduce the bug. Could you elaborate on your problem if it's still an issue.

**Comment by grechuu** [comment]
Tested on ptr tried to use agm 1st then nifty and vice versa but noone of thoose trinkets but other one on 5 min cooldown.
