### ISSUE TITLE
BRD - "The challenge"

### ISSUE THREAD

**Issue by willuseonly** [TeamEverlook/Everlook-BugTracker#308]
I completed 'The challenge' and got 'Top Piece of Lord Valthalak’s Amulet' quest, but it seems the NPC reclaimed it.I have Left Piece of Lord Valthalak’s Amulet and Right Piece of Lord Valthalak’s Amulet in my backpack, but not Top Piece of Lord Valthalak’s Amulet.
I saw online that this might be a BUG because after completing the quest, the quest item was reclaimed by the NPC but not returned, yet I can continue with the subsequent tasks. I’ve asked the NPC, but it seems they cannot provide me with the quest item again. I even reformed a team to defeat the quest boss again, but it didn’t drop the item. I’m at a loss now, so please, can a GM help me? I fear missing out on completing this quest would be a huge disappointment for me.
My GameID “Goodaunt” Human Warrior

**Comment by NiDiCi** [comment]
Hi Willuseonly,

From what I've heard this is a know issue, you can make a GM ticket and they will help you resolve your issue so that you can continiue with your quest. Will close this since it's a duplicate.
