### ISSUE TITLE
Orgrimmar Cloth Quartermaster: No Runecloth Hand in quest

### ISSUE THREAD

**Issue by SunnySaoirse** [TeamEverlook/Everlook-BugTracker#309]
The Cloth Quartermaster in Orgrimmar for orcs is not giving the Runecloth hand in quest for Orgrimmar reputation.

(https://www.wowhead.com/classic/quest=7824/a-donation-of-runecloth)

1. I went to the Drag in Orgrimmar, to the area where you learn tailoring so I can accept the quest.
2. I check in with Rashona Straglash, the Cloth Quarter Master for Orgrimmar reputation, but the quest was not available.

What I expected to happen was to just go into the building and see the quest available for me to hand in. But that's not the case, she's not giving out the quest.

![image](https://github.com/TeamEverlook/Everlook-BugTracker/assets/155837820/6e70da4a-d79e-4bd1-ae25-7c8b6275cfd9)

I've also went to the 3 other quarter masters to see if they were having the same problem. The tauren quarter master is also suffering this issue, while the Darkspear one is working just fine, and the undead quarter master gives the quest AFTER you hand in the other three first.

**Comment by mroreo3** [comment]
This issue has been resolved.
