### ISSUE TITLE
Zandalarian Hero Charm/Trinkets with charges

### ISSUE THREAD

**Issue by Maskinavfetting** [TeamEverlook/Everlook-BugTracker#312]
**Describe the bug**

The Charges of Zandalarian Hero Charm Gets eaten up by the jumps of Chain Heal, Healing wave(Full tier 1), Chain Lightning. 
It Should not do that. 

**Quest/Item/Spell Link**
https://www.wowhead.com/classic/item=19950/zandalarian-hero-charm
For the future these Trinkets is also relevant for the issue
https://www.wowhead.com/classic/item=22678/talisman-of-ascendance
https://www.wowhead.com/classic/item=23047/eye-of-the-dead

**To Reproduce**
1. Activate Zandalarian Hero Charm
2. Cast Chain Heal, Healing Wave(Full tier 1), Chain Lightning
3. Observe The Charges of the Trinket on the Buff Frame

**Expected behavior**

Only The Initial/Main Heal should eat The charges, not the Jumps, 
The + Heal power or + Spelldamage from trinket with charges should only affect the Main Heal or Damage Spell, not the jumps, Ingame class mechanics/set bonuses should take care of how much healing and damage the jumps does.
Here is a Youtube video for proof: 00:54, Trinkets get activated and shamans casts Chain Heal
https://www.youtube.com/watch?v=nK2DiM5mwbo

**Screenshots**

**Additional context**

**Comment by NiDiCi** [comment]
Hi Maskinavfetting,

I've know about this issue for a while, it happens to all classes using this trinket. I've tested this on shaman, mage, priest. It will lose charges based on the amount of targets affected by the skill and not by the amount of skills used. The same happens with all tested types of multi target skills.

**Comment by NiDiCi** [comment]
Hi Maskinavfetting,

With the most recent update this was fixed. Tested this on mage and shaman and had no issues.
