### ISSUE TITLE
Moonrage Darksoul

### ISSUE THREAD

**Issue by Cannon-DB** [TeamEverlook/Everlook-BugTracker#314]
**Describe the bug**
Moonrage Darksoul(s) in Silverpine forest when enraged do not seem to be a little strong against casters.

**Quest/Item/Spell Link**
https://www.wowhead.com/classic/spell=8599/enrage
https://www.wowhead.com/classic/npc=1782/moonrage-darksoul

**To Reproduce**
1.Attack Moonrage Darksoul
2.Lower the health of the mob to about half
3.Mob enrages
4.Rips spellcaster to shreds

**Expected behavior**
Not to Die in three to four hits while fighting 2 Moonrage Darksoul mobs. Kills the warlock tank pet in no time flat either.

**Screenshots**
![Screenshot 2024-01-15 215206](https://github.com/TeamEverlook/Everlook-BugTracker/assets/156735365/69a3c19c-d6f1-4cad-8f8a-94c42c8c28b1)
![Screenshot 2024-01-15 215337](https://github.com/TeamEverlook/Everlook-BugTracker/assets/156735365/a4b5fab6-49a8-4a8e-9eb5-dd9e3f2ad7ba)

**Additional context**
Seems they crit more often while enraged. When each hit on my warlock as a crit hits for 64 dmg of my 228hp pool hurts. 

If i'm over reacting just delete. xD

**Comment by grechuu** [comment]
Can't seem to find any issue with it critting me more often than usual, u probably just got pretty unlucky.
