### ISSUE TITLE
[AQ40] Anubisath Defender pull range is too big

### ISSUE THREAD

**Issue by HS-Disq** [TeamEverlook/Everlook-BugTracker#316]
**Describe the bug**
Anubisath Defender's pull range is back to 100 yards down from 30 yards. In addition, their social aggro is still 200 yards as opposed to 50 yards.

**Quest/Item/Spell Link**
https://classicdb.ch/?npc=15277

**To Reproduce**
1. Go to AQ40
2. Try pulling Anubisath Defender

**Expected behavior**
As this has Light's Hope values, the pull range should be enough for a hunter to get in range to shoot it (30-40 yards). Social aggro should not be higher than 50 yards.

**Comment by NiDiCi** [comment]
Hi HS-Disq,

This has now been reported as fixed and the range should be 50 yards, let us know if there is still any issues.
