### ISSUE TITLE
[AQ40] Qiraji Mindslayer damage

### ISSUE THREAD

**Issue by HS-Disq** [TeamEverlook/Everlook-BugTracker#317]
**Describe the bug**
Qiraji Mindslayer is no longer interruptible. That is how it was in Classic, but there is no cooldown to their abilities. They are using their Mind Blast and Mind Flay near constantly, causing massive damage to the raid. From 31k to the raid to 984k to the raid.

**Quest/Item/Spell Link**
https://classicdb.ch/?npc=15246

**To Reproduce**
1. Go to AQ40
2. Pull a pack with Mindslayers.
3. Watch damage.

**Expected behavior**
There should be a period of time where they can't spam their abilities. vMangos always had that issue where abilities with no cooldown cause them to spam it. Classic combat worked differently where they had a server side wide script to ensure abilities aren't spammed.

**Comment by NiDiCi** [comment]
Hi HS-Disq,

This problem arose together with the recent patch. This has been fixed on the ptr and should now pushed to the main server with the next server reset.
