### ISSUE TITLE
[ALL] Armor on mobs is too low

### ISSUE THREAD

**Issue by HS-Disq** [TeamEverlook/Everlook-BugTracker#318]
**Describe the bug**
Armor is set to 3637 for most bosses. This server was meant to represent Light's Hope which had armor hightened to a standard 4800 armor.

**Expected behavior**
This server was meant to represent Light's Hope which had armor hightened to a standard 4800 armor.

**Comment by NiDiCi** [comment]
Hi HS-Disq,

This problem arose together with the recent patch. This has been fixed on the ptr and should now pushed to the main server with the next server reset.
