### ISSUE TITLE
Quest not working - After the ambush

### ISSUE THREAD

**Issue by Musing63** [TeamEverlook/Everlook-BugTracker#336]
**Describe the bug**

**Quest/Item/Spell Link**
![Screenshot_267](https://github.com/TeamEverlook/Everlook-BugTracker/assets/32599665/89142bf8-9fe4-48d5-81bb-f4081449b70d)

If this is quest, item or spell related, please put the link here.

Example:  https://www.wowhead.com/classic/quest=5904/a-plague-upon-thee

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by NiDiCi** [comment]
You need to actually fill in the template not just send the templet.
