### ISSUE TITLE
Berserker Rage not working as intended

### ISSUE THREAD

**Issue by ezzekielfox** [TeamEverlook/Everlook-BugTracker#356]
The Warrior skill "Berserker Rage" does NOT generate additional rage when struck by a direct attack.

**Expected behavior**
You should generate 1-2 additional rage (maybe more, unsure on exact numbers) when struck by any direct attack.

**Comment by jensbond420** [comment]
Seem to work just fine, 30% more rage gained from Physical Damage taken. Open another Issue if you have more info.

No Berserker Rage (Video 1)
Damage Taken - Total Rage - Rage Gained from hit
1538 - 16 rage +16
1521 -33 rage +17
978 - 43 rage +10
1428 - 59 rage +15
1509 - 75 rage +16
1621 - 92 rage +17


https://github.com/user-attachments/assets/8228e7f6-cae4-478c-9592-44771365d536



Berserker Rage (Video 2)
Damage Taken - Total Rage - Rage Gained from hit
1570 - 22 rage +22
1637 - 45 rage +23
1506 - 66 rage +21
960 - 79 rage +13
1370 - 99 rage +20


https://github.com/user-attachments/assets/9b9fe48d-ad63-444e-af7a-96982fddb8af
