### ISSUE TITLE
Mobs can parry while casting

### ISSUE THREAD

**Issue by Marty123asd** [TeamEverlook/Everlook-BugTracker#359]
**Describe the bug**

**To Reproduce**
1. Attack mob with casted spells
2. Wait until they cast
3. Use ability 

They might parry/dodge

**Comment by jensbond420** [comment]
What mob exactly? I've tested on Scarlet Spellbinder 4494 and it has not Parry/Dodge a single attack while casting.

Tested over 1000 White attacks, 100 Heroic Strike/Bloodthirst and 15 Pummels. 0 Dodge/Parry

**Comment by jensbond420** [comment]
Putting it as closed, please make a new bug report If you have more info.
