### ISSUE TITLE
Oily Blackmouth

### ISSUE THREAD

**Issue by Xykyta1** [TeamEverlook/Everlook-BugTracker#369]
https://www.wowhead.com/classic/item=6358/oily-blackmouth - fish and all the right locations for fishing.

Found this fish in Stormwind and Darkshore. Perhaps can be found in others low lvl zones too.

**Comment by jensbond420** [comment]
According to this source, the waters of Stormwind Canals and Darkshore are supposed to drop Oily Blackmouth https://wowwiki-archive.fandom.com/wiki/Fishing_locations#Fishing_skill_levels_by_zone
![oily blackmouth1](https://github.com/user-attachments/assets/890a6f0a-4ff9-48b2-9335-97dd84a5ff20)

**Comment by jensbond420** [comment]
Not a bug
