### ISSUE TITLE
The item "Flayed Demon Skin" is bugged

### ISSUE THREAD

**Issue by caordonezb** [TeamEverlook/Everlook-BugTracker#373]
**Describe the bug**
I looted the item "Flayed Demon Skin" and should give me the quest "The Corrupter" but when I clicked on the object nothing happened

**Quest/Item/Spell Link**

Item:
https://www.wowhead.com/classic/item=20310/flayed-demon-skin
Quest:
https://www.wowhead.com/classic/quest=1480/the-corrupter

**Expected behavior**
I expect that by clicking on the item you can accept the quest

**Comment by Simp-N** [comment]
If you're using 1.14, try logging in on 1.12 and starting it, then you can log back on 1.14.

If you're using 1.12, try deleting WDB.
