### ISSUE TITLE
CoS and CoE and negative Resi 

### ISSUE THREAD

**Issue by Tuirenn** [TeamEverlook/Everlook-BugTracker#41]
**Describe the bug**
Since yesterday someone or something fixed the Warlocks spell and gave negative Resi to mobs and player. 

**Quest/Item/Spell Link**
It was yesterday in the code why not today anymore ?

**To Reproduce**
1. cast CoS on mob.
2. Cast shadowbolt
3. No profit x.x

**Expected behavior**
To work like it was to 1 Day ago, till the AQ patch will dropp and it will be like Vanilla was.

**Screenshots**
It's a code thing so well there isn't

**Comment by reddeffect** [comment]
I think we are reporting same bug https://github.com/TeamEverlook/Everlook-BugTracker/issues/55

**Comment by Tuirenn** [comment]
> I think we are reporting same bug #55

Yes we are, it's now 3 days in and still waiting :)
