### ISSUE TITLE
i'm snowman and i can't play

### ISSUE THREAD

**Issue by Equlipce** [TeamEverlook/Everlook-BugTracker#42]
Dear GM, hello, my game ID is Equlipce,I used a reward item I got in the winter festival quest chain and I used the item and it turned me into a snowman and it won't let me do anything and when I try it says I'm stunned
![WoWScrnShot_122822_151307](https://user-images.githubusercontent.com/121576950/209861325-554ad3ab-8d42-499a-98e6-9de70f50b377.jpg)

**Comment by battlelook** [comment]
double click the buff top right

**Comment by Equlipce** [comment]
thanks
