### ISSUE TITLE
buffing players not possible

### ISSUE THREAD

**Issue by battlelook** [TeamEverlook/Everlook-BugTracker#46]
**Describe the bug**
I had this bug in several dungeons and another druid also told me about it.
I buffed my group normally with MotW and the tank with thorns.
One Player of my group could not be buffed. 
The spell went through, mana was deducted, but no buff was shown on the target.
A relog of the player helped and I could buff him normally again. Without relog it does not go away
Observed yesterday and today.

**Quest/Item/Spell Link**
Mark of the Wild, Gift of the Wild, Thorns

**Comment by HS-Disq** [comment]
We have noticed this with our paladins as well in MC today where greater blessings were applied except to one person. That person had to get a small blessing and then the greater one works again.

We had this happen with 2 paladins (with 2 different blessings) at 2 different people at a random interval.

**Comment by Gamemechanicwow** [comment]
By any chance was it warriors that didn't receive the buffs?

**Comment by HS-Disq** [comment]
Yep, it was indeed warriors that weren't getting it.

**Comment by Gamemechanicwow** [comment]
Fixed in vmangos here: https://github.com/vmangos/core/pull/1763

**Comment by HS-Disq** [comment]
Ah cool. Looks like it's not in vmangos:production yet, only in development, but glad to see it is fixed at least in development. :)

**Comment by NiDiCi** [comment]
As far as I know this is fixed and no longer an issue like previous comments mention, will close this issue.
