### ISSUE TITLE
Melee Missing in PvP

### ISSUE THREAD

**Issue by HS-Disq** [TeamEverlook/Everlook-BugTracker#51]
**Describe the bug**
Melee hit cap in pvp for a 2 hander is 5%. Currently, I am still missing yellow abilities even with 6% hit cap in pvp.

**Quest/Item/Spell Link**
n/a

**To Reproduce**
1. Engage in PvP with 6% hit.
2. Duel a mage (last seen was against a mage and they have no +def)
3. Cast Mortal Strike or white hit, see it miss

**Expected behavior**
At 5% hit, no white hit or yellow hit can miss with a 2hander.

**Screenshots**
Will add next time.

**Comment by HS-Disq** [comment]
![image](https://user-images.githubusercontent.com/21331842/209942156-6416bd01-5451-4611-b2a0-8a21c7432574.png)
Hamstring miss against a rogue (no evasion).

**Comment by HS-Disq** [comment]
![image](https://user-images.githubusercontent.com/21331842/209955027-c41717be-2720-4b67-b80d-093d74827e35.png)
execute and melee swing miss against a warr (might be +def)

**Comment by HS-Disq** [comment]
![image](https://user-images.githubusercontent.com/21331842/209957675-caa26a7b-b5a3-4169-b49c-e7a13bfe6bc2.png)
hamstring miss on a 57 pet.

**Comment by HS-Disq** [comment]
![image](https://user-images.githubusercontent.com/21331842/209961347-81276cc6-d8ae-4ae1-8fc7-f7eb9ff3767d.png)
Overpower miss on a hunter

**Comment by HS-Disq** [comment]
The above screenshots were made with 6% hit. Future screenshots will be made with 8% hit.

**Comment by HS-Disq** [comment]
![image](https://user-images.githubusercontent.com/21331842/210011990-74e0e90f-33bc-4dc7-abbf-9d7b26821538.png)
hamstring miss against bear.

**Comment by HS-Disq** [comment]
![image](https://user-images.githubusercontent.com/21331842/210016224-abce300a-4c29-41c8-9633-975b524e82d5.png)
hamstring miss against warrior

**Comment by HS-Disq** [comment]
![image](https://user-images.githubusercontent.com/21331842/210016889-c69c0abc-d793-4fe7-a3d4-b5089173c611.png)
hamstring miss against warrior

**Comment by HS-Disq** [comment]
![image](https://user-images.githubusercontent.com/21331842/210058702-a7fd6b96-d157-4854-84b6-2a448ae7b05f.png)
MS miss against a warrior

**Comment by HS-Disq** [comment]
The above comments should show that 8% hit does miss less, but it's still happening. I am now going to up my weapon skill to 300 to see if that alters it (it shouldn't except against pets).

**Comment by HS-Disq** [comment]
Haven't had a miss since my weapon skill is 300/300 at 6% hit, will upload when new one came in.

**Comment by HS-Disq** [comment]
no miss has come in, looks like this server takes weapon skill into account. Not buggy, but weird behavior.

**Comment by sh3ppard** [comment]
The miss chance depends on your weapon skill. The **base miss chance = 5%.**
```c++
missChance = 5;
```
Formula for PvP (player vs player):
```c++
skillDiff = WeaponSkill - DefenseSkill
skillDiffBonus = skillDiff * 0.04
missChance = missChance - skillDiffBonus;
```
So for example you are 60 lvl and has 200 weapon skill for your weapon and you hit 60 player with 300 defense skill then:
```c++
skillDiff = 200 - 300 = -100
skillDiffBonus = -100 * 0.04 = -4
missChance = 5 - (-4) = 5 + 4 = 9
```
4% will add to base miss chance = 9% in total

[Source](https://github.com/vmangos/core/blob/ea4b8c1c9418cb08fbb1fc6707dd37c597b1b5f1/src/game/Objects/Unit.cpp#L2516).

**Comment by red-candle** [comment]
There are a shitton of bugs. Almost none of my spells were resisted in AV when I was 56-59. As soon as I hit 60, 10% spell resist on everything.
