### ISSUE TITLE
Curse of elements and shadows not providing spell vulnerability

### ISSUE THREAD

**Issue by reddeffect** [TeamEverlook/Everlook-BugTracker#55]
**Describe the bug**
Curse of elements and curse of shadows are no longer enabling spell vulnerability due to negative resistance

**Quest/Item/Spell Link**
https://classicdb.ch/?spell=17937
https://classicdb.ch/?spell=11722

**To Reproduce**
1. Cast curse of elements or curse of shadows on a mob
2. Attack mob with a school of magic relative to the curse (curse of shadow and shadow bolt spam mob)
3. vulnerability damage no longer occurs

**Expected behavior**

We posted some links a while ago when discussing the mechanics with Wall during the PTR. https://i.redd.it/7dofxuwtki931.jpg has some vanilla era negative resist photos.

Wall post about implementation:
https://discord.com/channels/973529971740008448/1007293981035597935/1036337548907266078
This is the table that Wall used:
https://discord.com/channels/973529971740008448/1007293981035597935/1036363167061782529
This is Wall posting pic of implementation which we tested on the PTR:
https://discord.com/channels/973529971740008448/1007293981035597935/1036392185362395237
Wall worked with brotalnia to get it pushed upstream
https://discord.com/channels/973529971740008448/1007293981035597935/1036313139232391198
(Credit to Darg#0232 on everlook discord for information related to this work during the PTR)

bonus spell vulnerability damage when targets have negative resistance to certain magic schools
Screenshots of spell vulnerability working for curse of shadows 
![image](https://user-images.githubusercontent.com/17356658/209992050-5b95488e-e2f5-46a8-97c8-c3b34fac1083.png)
![image](https://user-images.githubusercontent.com/17356658/209992131-b39cb69b-37e2-4ab8-9b9b-e57c695c9363.png)

**Screenshots**
**Here is an image of it not working**
![image](https://user-images.githubusercontent.com/17356658/209991788-b99f2dd5-01b6-4fab-ab1d-c40db487a039.png)

**Additional context**
![image](https://user-images.githubusercontent.com/17356658/209991863-16682f5a-2eae-44f8-a2ff-920938db9cfd.png)

removal of mechanic should not occur until patch 1.9

**Comment by Tuirenn** [comment]
I created a ticket 1 Day ago here and in-game, waiting for someone to read it

**Comment by GomOnHyjal** [comment]
Please fix this ASAP, staff. Commenting for more visibility.

**Comment by Bobdoore** [comment]
Hey I leveled a warlock and was having a blast, noticed my Curse of Shadows isn't doing what it did originally. What's going on. Looks like the gentleman above figured it out and posted it quite clearly. Please fix this.

**Comment by reddeffect** [comment]
Issue is occuring again since last week
