### ISSUE TITLE
bug 不能骑马

### ISSUE THREAD

**Issue by c4uoliwen** [TeamEverlook/Everlook-BugTracker#58]
**To Reproduce**
1. 我在everylook中是一名亡灵法师 Oliwen
2. 在游戏中我学习了亡灵骑术和购买了红色骸骨军马，但是不能骑马。提示需要骑术75。
3. 在骑术训练师那里可以看到已学习骑术。

**Expected behavior**
让我能骑坐骑，谢谢

**Comment by battlelook** [comment]
删除WDB文件夹

**Comment by pandasd** [comment]
Holy fuck, try to use english.
