### ISSUE TITLE
Gaodu Hunter lvl 60 

### ISSUE THREAD

**Issue by nigma133** [TeamEverlook/Everlook-BugTracker#63]
**Describe the bug**
This character  has more than 50 day played ( he never logged off more than 20minuts since the server started )
Could you please do something , We premade PVP lvl 60 and he do  more than us as solo Q  24/24 7/7 since the start. , it would be great.

**Screenshots**
(https://gyazo.com/ad7f22116340fba1467388f8a37fad53)

**Comment by sh3ppard** [comment]
He got banned a long time ago.
