### ISSUE TITLE
Cannot Ride Horse

### ISSUE THREAD

**Issue by Oucl123** [TeamEverlook/Everlook-BugTracker#65]
Dear Everlook team

After i bought the riding skill, it didnt show up and when i try to directly ride the horse it said i havent learn riding yet. But i am sure i learned the skill and when i open riding teacher says i already learned. I cant find the riding skill in my skill book and i tried to delete the WDB AND WTF fold to make it work but still not sucess.
May i get some help?

Yours sincerely 
Oucl

**Comment by Oucl123** [comment]
Alg now i delete game and redownload then it work

**Comment by dimadze1337** [comment]
No need to game delete omegalul, just clear your wdb folder.

**Comment by NiDiCi** [comment]
Hi Oucl123,

Happy that you got it to work but I do think like mememully says you could have just deleted the wdb folder that should fix the issue. If it happens again test that or make a ticket on discord to contact a GM.
