### ISSUE TITLE
Hunter pet bypass stealth

### ISSUE THREAD

**Issue by exequtor1** [TeamEverlook/Everlook-BugTracker#68]
There is a bug about hunter pets in PVP. If the hunter sends its pet attacking you, it is ignoring if you go stealth meanwhile. It keeps targeting you and will attack you in stealth too. 
It should work like in the case of players: if the rogue goes stealth, your enemy has to lose its target. But the hunter pet does not lose it, bypassing the stealth.

**Comment by sh3ppard** [comment]
its not a bug.
It was in vanilla.

[Source](https://www.wowisclassic.com/en/news/hotfixes-12-november/).
