### ISSUE TITLE
Quest "A Final Blow" stays at "Moore slain: 0/1"

### ISSUE THREAD

**Issue by Bamboozle0101** [TeamEverlook/Everlook-BugTracker#69]
**Describe the bug**
Cannot complete the horde quest "A Final Blow", the quest stays at "Moore slain: 0/1" even tho it's been killed more than once,
restarted the game, killed him again, nothing

**Comment by Gamemechanicwow** [comment]
Try with the 1.12 client. Hermes proxy/1.14 issue with quest progression packets.

**Comment by Bamboozle0101** [comment]
Thanks a lot, worked
