### ISSUE TITLE
Out of combat duration

### ISSUE THREAD

**Issue by Francesq** [TeamEverlook/Everlook-BugTracker#7]
**Describe the bug**
After engaging a pvp fight, the duration to be out of combat is too long. I notice it, while playing rogue because you are supposed to be out of combat before the end of 3/3 imp gouge 5.5 sec).

**To Reproduce**
0. Pick up you rogue with 3/3 imp gouge (any rank is ok)
1. Begin fight with pvp target (duel or opposite faction)
2. Gouge your target
3. Spam stealth
4. See you can't stealth before the end of gouge

**Expected behavior**
You are supposed to be able to restealth before the end of gouge then you can cheap shot again or sap your target (so you and your target are supposed to be out of combat before the end of 3/3 gouge).

**Additional context**
This bug is not really easy to highlight since wow wiki say it is 6 sec duration but it is not. Other sources are talking about 5 sec and I can prove this is the truth : 

I have seen this video posted on YouTube there is 15 years ago so no private server, only official ones.

https://youtu.be/8BXl_ZYiEqA

At 5:40

We can see before the end of the gouge (showed by NECB add on) stealth icon becomes active which means he is out of combat in less than 5.5 sec, but he probably doesn't know it because he uses kidney shot instead of Cheap shot...

This move is not easy to set so to give advice to the dev, you can put stealth and sap or stealth and cheap shot on the same bind (unstealth and stealth binds) so you just have to spam your key to do it.

Hope you could fix it soon cause it really penalize rogue in wpvp...

**Comment by Neto-WoW** [comment]
Could you please provide video evidence of your experience on Everlook?

**Comment by sh3ppard** [comment]
Found this comment: https://www.wowhead.com/classic/spell=1856/vanish#comments:id=2793928
> **By gunfella2000 [on 2006/09/21] (Patch 1.12.0)**
> If you are in combat and you want to restealth do not use vanish. A simple but effective trick that I do mulitple times in combat, is Gouge followed by rapidly tapping the Z key. What this done is it takes you out of combat quicker, (Usualy before Gouge is finished with duration, and allows you to re-stealth.

**Comment by sh3ppard** [comment]
I found the answer. The server [code](https://github.com/vmangos/core/blob/75474d2d33bccfabc2a2f05986132529f3b79cbb/src/game/Objects/UnitDefines.h#L68) talks for himself.
**Out of combat duration** must be **5.5 seconds** on Everlook.

**Comment by NiDiCi** [comment]
I tested this and it seems just as @sh3ppard says that the out of combat duration is 5.5 seconds. All of the infromation online I can find online says that the Out of combat duration is supposed to be 6 seconds but I can't find something suggesting that it should be less then 5.5 seconds. I'm going to close the issue but if you are able to find documentation or video proof clearly showing the out of combat duration being less then 5.5 seconds make a new issue and I will look it over again.
