### ISSUE TITLE
Feign death will kill you

### ISSUE THREAD

**Issue by jowahl** [TeamEverlook/Everlook-BugTracker#71]
**Describe the bug**
I used feign death. After 6 minutes the effect expired, resulting in immediate death. No damage was taken according to combat log.

**Quest/Item/Spell Link**
https://www.wowhead.com/classic/spell=5384/feign-death

**To Reproduce**
1. Use ability Feign Death
2. Wait for 6 minutes until effect expires
3. Die

**Expected behavior**
I expected not to die.

**Comment by Gamemechanicwow** [comment]
Not a bug. FD will kill players on expiration in vanilla. This was changed with TBC.

![image](https://user-images.githubusercontent.com/2223066/211169112-33a5205c-f4d4-4a7e-8e41-c62a9820a5d8.png)
