### ISSUE TITLE
Can't have the mission

### ISSUE THREAD

**Issue by Oucl123** [TeamEverlook/Everlook-BugTracker#76]
Dear Everlook team

I cant get the mission Warlord's Command. I am lvl 60 but when i go there and chat with him I cant get the mission. There was no letter in my bag.
Any chance help me solve the problem?

Yours sincerely
Oucl

**Comment by Simp-N** [comment]
Are you also atleast Friendly reputation with Orgrimmar? I believe that is a requirement.

**Comment by Oucl123** [comment]
Ah thank you发自我的手机-------- 原始邮件 --------发件人： Simp-N ***@***.***>日期： 2023年1月12日周四 半夜12:17收件人： TeamEverlook/Everlook-BugTracker ***@***.***>抄送： Oucl123 ***@***.***>, Manual ***@***.***>主    题： Re: [TeamEverlook/Everlook-BugTracker] Can't have the mission (Issue #76)
Are you also atleast Friendly reputation with Orgrimmar? I believe that is a requirement.

**Comment by NiDiCi** [comment]
Hi Oucl123,

I hope this has been solved but for the future I think it's best if you make a ticket on discord for these kinds of things. Unless you have something more concrete that we can test or figure out I cannot do much to help. In these cases it's best to talk to a GM and they will hopefully be able to point out how you should procede.
