### ISSUE TITLE
my character is gettting net projector backfire upon every login

### ISSUE THREAD

**Issue by cruisecntrl** [TeamEverlook/Everlook-BugTracker#78]
**Describe the bug**

Everytime I login, the Net-o-Matic Projector trinket backfires and nets me in place for full duration. even with the trinket in my bank off my character. I still get it. its not written into any macro or anything seems to have randomly started happening after a hard DC.

**Quest/Item/Spell Link**
If this is quest, item or spell related, please put the link here.

https://www.wowhead.com/classic/item=10720/gnomish-net-o-matic-projector

**To Reproduce**

Everytime I login.

**Expected behavior**

not to get netted upon login.

**Screenshots**

![netted upon login](https://user-images.githubusercontent.com/122329851/211444159-69f9dc91-f205-4379-bda5-a8ff127fd6da.jpg)

**Additional context**

My character name is Xo - Orc Hunter. my character may be bugged? not sure doesnt happen to other people I know who have the trinket.

**Comment by pikwako** [comment]
I have the same issue.
Sababa troll hunter 50

**Comment by sh3ppard** [comment]
Should be add [fix](https://github.com/vmangos/core/commit/5d73b39781437fc2d86e0eba87ad4cbf556542de) soon.

**Comment by HS-Disq** [comment]
This was fixed as per Neto:

Items]
  ⦁ Prevent net-o-matic from backfiring upon login [vMangos Team]
