### ISSUE TITLE
Earth bind totem getting rogue out of stealth

### ISSUE THREAD

**Issue by Francesq** [TeamEverlook/Everlook-BugTracker#8]
**Describe the bug**
Shaman earthbind totem unstealth rogues.

**To Reproduce**
1. Engage fight with a shaman (duel or pvp)
2. Let him use earth binding totem
3. You will be unstealthed if you go in the range of the totem or if you are in the range of the totem

**Expected behavior**
Since it does not deal any damage, earthbind totem is not supposed to unstealth target. This is like frozen trap which doesn't unstealth any player in the active area.

**Additional context**
I will add sources asap
If you have it, feel free to comment this issue.

**Comment by Newfriendfromwinter** [comment]
On Classic and other private servers, only the first tick unstealthed rogues.  This doesn't constitute evidence.

**Comment by Neto-WoW** [comment]
If you can find evidence from Classic or from original Vanilla I'll take a look.

**Comment by Gamemechanicwow** [comment]
fixed here: https://github.com/vmangos/core/commit/aba04e2bf56aa77188c85bed5a6d8ec361a77272
