### ISSUE TITLE
Tome Arcane Brilliance is not in game

### ISSUE THREAD

**Issue by cycoconutz** [TeamEverlook/Everlook-BugTracker#80]
All online references say it should be included in 1.3 patch (the other class buff books are in)

**Comment by Simp-N** [comment]
In vmangos it becomes available in 1.4. [Wowwiki](https://wowpedia.fandom.com/wiki/Arcane_Brilliance?oldid=6566749) has it listed as being added in 1.4, and I cannot find any mention of it from a date as early as 1.3. If you have some evidence it should be available in 1.3 I'd love if you shared them.

Also, [1.4 patch notes](https://wowwiki-archive.fandom.com/wiki/Patch_1.4.0)
> New Spell: Arcane Brilliance (available at level 56 - Loot) - Infuses the target's party with brilliance, increasing their Intellect.

**Comment by cycoconutz** [comment]
Huh I see what you're saying on the wowwiki. The classic.wowhead site has
1.3. So we definitely know it was .3 or .4 😅. I'm definitely not
suggesting to jump the gun, but other classes have their group buffs which
is why I assumed it should be in as well.

https://www.wowhead.com/classic/spell=23028/arcane-brilliance

**Comment by cycoconutz** [comment]
Just found this comment from wowhead as well:[image: image.png]

**Comment by Simp-N** [comment]
@cycoconutz 
![](https://cdn.discordapp.com/attachments/1063113248062320801/1063129123691692032/0.png)

https://www.wowhead.com/classic/item=18600/tome-of-arcane-brilliance#comments

**Comment by grechuu** [comment]
Not a bug.
