### ISSUE TITLE
Mother's Milk Bug (Unable to complete the quest despite having the debuff)

### ISSUE THREAD

**Issue by ghost** [TeamEverlook/Everlook-BugTracker#84]
(1.12.1 client)

Accepted Mother's Milk before entering LBRS, got poisoned (Mother's Milk icon appeared), debuff with constant net stuns started happening.

Entered mage portal to orgrimmar 20-30 seconds after debuff, took zeppeling and flight path back to NPC, could not deliver quest (grey icon on continue).  Shaman said he could not see the debuff on me (icon was instead on my UI).

Outside the dungeon the debuff icon was there (as you can see in the screenshot) but a weird throw net animation kept playing (while giving no stun or slow to me or anyone else) even on horseback/flying. 

I reentered the dungeon and the stun effect started happening again with the same throw net animation (I suppose working as intended). I HS to orgrimmar and repeat the process again (I also abandoned this time and retaken the quest with no effect). Same behaviour, outside i could walk with no stun (with every 5 seconds the weird throw animation happening) inside the effect would reappear.

Debuff finally cleared when I tried to enter LBRS again and a group of 10 allies attacked me while I was entering (i trinketed and shield walled and survived) once inside LBRS the debuff was gone. No death at all of course, from accept quest to this point. 

Yes It was dumb to do this quest now I know why.

**Quest link:** 
https://www.wowhead.com/classic/quest=4866/mothers-milk#comments

**To Reproduce**
Get Milk effect from spider boss in LBRS
Mage makes portal to orgrimmar
Have the stun effect happen 3-4 times before entering portal
Enter portal by jumping at the same time (I suppose) that the throw animation happens.
Lose 3h of your time trying to get help.

**Expected behavior**
Be able to turn in and complete quest as the debuff is clearly active.

**Screenshots**
![bugged_milked_small](https://user-images.githubusercontent.com/122573387/212193239-1b3eac75-6b2c-4660-8a62-a3746e632d80.png)

**Additional context**
Made a GM ticket to which GM Torvon replied that since a screenshot can be faked he wouldn't complete the quest for me and kindly advised to make a bug report. Not gonna lie, I was kinda pissed but maybe something can be done about this.

**Comment by Goloh926** [comment]
I have the exact same issue; see below: 

![MM1](https://user-images.githubusercontent.com/122648670/212427701-1858f052-957b-4168-9d5f-6cfdae8aef66.jpg)

I tried a method of solo-ing this as hunter by using my pet, feign death, and an invisibility potion. I got the boss to poison me, feigned death to exit combat, and used my hearthstone to teleport to Kargath. From there I took the flight to Flame Crest in Burning Steppe - I remember hearing the net sound effect during the short flight. I had the debuff for the entire trip. I arrived at Ragged John and have the same problem. I logged out with the debuff so I still have it. Will ping a GM in-game.

**Comment by ghost** [comment]
Interesting. Let's hope the GM completes the quest for us this time and the bug gets fixed.

**Comment by ghost** [comment]
Unfortunately I'm unable to reproduce this. It seems to work fine. The "Milk me" dialogue is not inside the quest, its in the dialogue when you open chat with the npc. Try disabling addons and clearing wdb.

![image](https://user-images.githubusercontent.com/79717052/215407961-a9d40621-8470-439d-8644-c8299fdd2905.png)
