### ISSUE TITLE
Bug in the talent tree of druid.

### ISSUE THREAD

**Issue by waytoodesp** [TeamEverlook/Everlook-BugTracker#89]
Current patch: 1.3
Character Nickname: Desq

**Describe the bug**
The bug concerns the talent tree, as a Druid.
After putting 2 points in the Balance tree, one in Nature's Grasp and the other in Improved Nature's Grasp.
Only the point in Improved Nature's Grasp is visible, like if I never did put a point in Nature's Grasp which is impossible.
Also, it says I only have put one point into the tree while in reality there are two.
The issue I think could happen is if I try to put the point again in Nature's Grasp I would loose one point out of my 61.
I also don't have Nature's grasp rank one anymore, only from the rank two, three, etc..

**Screenshots**
LVL 39:
![image](https://user-images.githubusercontent.com/122754463/212569315-6b17e92e-7d29-470b-b6f1-a7057e3da200.png)
![image](https://user-images.githubusercontent.com/122754463/212569321-46c126b5-7a20-4dc2-aea4-3d5f48e8e678.png)
![image](https://user-images.githubusercontent.com/122754463/212569326-b9f9c755-a4e7-4d28-8f4e-df096c140252.png)
![image](https://user-images.githubusercontent.com/122754463/212569339-34bffe57-88e4-4d54-9ce0-b0b10a95ee3d.png)
LVL 40:
![image](https://user-images.githubusercontent.com/122754463/212573537-f4fc3c42-5624-4005-9c12-83a97e59e7a7.png)

**Comment by dimadze1337** [comment]
It is a problem with your UI/client, not with the server.

**Comment by Godmatik** [comment]
@waytoodesp disable addons, it might be zygor
