### ISSUE TITLE
Rogues Vanish grants Immunity to Everything(?)

### ISSUE THREAD

**Issue by Trastjok** [TeamEverlook/Everlook-BugTracker#9]
Failed to get rogues out of Stealth with Arcane Explosion/Blizz/CoC right after Vanish even though they stand right next to me in stealth.
They seem to be immune for 1-1,5 seconds.

1. Let rogue Vanish
2. Cast immediately an AoE spell in his range

**Expected behavior**
He should be taking damage immediately after vanish and taken out of stealth.

**Comment by Neto-WoW** [comment]
![image](https://user-images.githubusercontent.com/79717052/208279678-d12d2211-1ce4-460a-b1cb-30af3efd1592.png)

Apparently there were many fixes for Vanish. It looks like for the first second this is still the case. Still, I tried testing to replicate your issue and couldnt.

https://imgur.com/a/gSHH8zm

**Comment by NiDiCi** [comment]
I tested this today and it does happen. I can reproduce the issue but this is a commonly know thing and I do not believe it's a bug. I will close this issue.
