### ISSUE TITLE
RIch Thorium in DME

### ISSUE THREAD

**Issue by orlymike** [TeamEverlook/Everlook-BugTracker#90]
**Describe the bug**
Most of the time when I am in DME, I cant mine one of the RTV and sometimes both. I have 300 mining and tried with the +5 glove enchant

**Quest/Item/Spell Link**
n/a

**To Reproduce**
1. Go to rich thorium vein
2. click to mine
3. doesnt give full mining bar animation. instantly says failed attempt. no matter how long i spam click it.

**Expected behavior**
expect o mine the vein

**Comment by orlymike** [comment]
https://i.imgur.com/98Cnv4T.jpeg
<blockquote class="imgur-embed-pub" lang="en" data-id="a/6T3520p" data-context="false" ><a href="//imgur.com/a/6T3520p"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
<blockquote class="imgur-embed-pub" lang="en" data-id="jaa8xIR"><a href="https://imgur.com/jaa8xIR">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by sh3ppard** [comment]
Did you kill the last boss before?

**Comment by orlymike** [comment]
Yes of course?

**Comment by sh3ppard** [comment]
Looks like script bugged which should be unlock those veins. I have that issue when we wiped on last boss and door into cave was open.

**Comment by pandasd** [comment]
It looks like you're trying to cheat by passing through the doors and cave via bad internet speed emulator and spam of logoff/logon. It won't work like that omegalul

**Comment by orlymike** [comment]
No program or emulator was used. Just relogging. Cleaver use of game
mechanics.

**Comment by sh3ppard** [comment]
> No program or emulator was used. Just relogging. Cleaver use of game mechanics.

So vManGos fixed that _abuse_ I guess. Also as some stuff to prevent farm DM by mages.

**Comment by NiDiCi** [comment]
I can't reproduce this problem while the boss is alive. Made a separate issue that while the boss is alive you can't mine all nodes. 

If this is still an issue could you give some more details to how this happens.
