### ISSUE TITLE
skill display bug

### ISSUE THREAD

**Issue by sevenc4a** [TeamEverlook/Everlook-BugTracker#91]
when player use skill on  the earth's surface，as Entangling Roots,Totems，the effects not disappear... pic--https://imgloc.com/i/HDeAa
https://imgloc.com/i/HDxBz      https://imgloc.com/i/HDzrx

**Comment by sh3ppard** [comment]
I have the same issue only on 1.12 client. Looks like it is client side issue. Heard once about that issue from someone else. Seems it happens rarely. I don't know how to fix it but someone told me it may causes by newest video driver so need to install the oldest one but I didn't try. I just use 1.14 client instead.
![image](https://user-images.githubusercontent.com/121023853/213140322-8c4e1f3e-c22c-4adf-b140-e67c8e062cc6.png)

**Comment by sevenc4a** [comment]
> I have the same issue only on 1.12 client. Looks like it is client side issue. Heard once about that issue from someone else. Seems it happens rarely. I don't know how to fix it but someone told me it may causes by newest video driver so need to install the oldest one but I didn't try. I just use 1.14 client instead. ![image](https://user-images.githubusercontent.com/121023853/213140322-8c4e1f3e-c22c-4adf-b140-e67c8e062cc6.png)

yeah,ty mate,Thats video driver problem,update it can fix that,Its not sever bug,sry GM guys!
