### ISSUE TITLE
[Warrior] Occassionally unable to charge

### ISSUE THREAD

**Issue by HS-Disq** [TeamEverlook/Everlook-BugTracker#92]
**Describe the bug**
Sometimes you are unable to use charge while mounted as it will error out that it says "You are mounted". I have only noticed this in Warsong and only occassionally. It is not consistent. Sometimes the UI doesn't show the mount icon, but your character is still on the mount visually.

**Quest/Item/Spell Link**
Mount

**To Reproduce**
1. Go to Warsong
2. Die
3. Mount
4. Try to charge something
5. Sometimes result, most often works.

**Expected behavior**
It should never bug out like that

**Screenshots**
This is a screenshot where I am trying to charge someone. Not in combat, still unable to charge. Even while in combat, it should dismount me. It's not doing it.

![image](https://user-images.githubusercontent.com/21331842/212997179-eac25476-746f-4072-89f6-3d8a30c82831.png)

**Additional context**
Using the addon LazyPig to auto dismount me when I charge, but even when I try to manually dismount, it won't let me. Once it happens, I am stuck on mount until I go indoors somewhere.

**Comment by HS-Disq** [comment]
I should note that while I am visually on my mount, I can't use any abilities.

**Comment by dimadze1337** [comment]
Use Ezdismount addon. Not a bug at all.

**Comment by HS-Disq** [comment]
This issue has no longer occurred. The culprit was an outdated LazyPig. Issue resolved.
