### ISSUE TITLE
Riding can not be used

### ISSUE THREAD

**Issue by jie889977** [TeamEverlook/Everlook-BugTracker#95]
Report bugs：
Hello there！I learned riding in the East logging valley. It didn't work but the gold coins I learned were deducted. I still can't ride a horse after I bought it. By the time I got back to the equestrian trainers, there were no more events to study. Please help me to solve this problem, thank you.
This is my id：Stonemage

**Comment by Gamemechanicwow** [comment]
Close wow. Delete wdb folder.
